The-Alpha-Project/alpha-core

game/world/managers/objects/player/InventoryManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/SellItemHandler.py
Item selling adds the handler itself, sell error sending and a method for getting an item by it's guid from an inventory (I did not find an existing way to do it easily).
Second commit is a small fix for stacking - items were duplicated after relogging.
=> Item selling + inventory item stacking fix

game/world/managers/objects/player/InventoryManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/BuyItemInSlotHandler.py
add_item now also returns a boolean instead of the item since it can end up in multiple stacks. There are also some small minor formatting changes to make lines more readable.
Add_item_to_slot is mainly based on functionality that I've observed on other servers, what actions have error messages tied to them and what feels intuitive.
=> Implement BuyItemInSlot, fix add_item and can_store item stack checks

etc/docker/build_sql_patches.sh
the script that initializes the docker sql DB doesn't work anymore. This path fix repairs it.
=> fixed docker db init script path

.gitignore
These folders are required to be in **gitignore** file for developers that are using VS Code as IDE and Virtualenv.
=> Added vscode and venv folders to gitignore

game/world/WorldManager.py, game/world/opcode_handling/handlers/interface/AuthSessionHandler.py
/ Handle Auth challenge before launching any threads or queues.
/ Set a 120 second timeout to world socket,.
/ Avoid multiple calls over socket.shutdown() and socket.close()
=> Error AuthCodes should now properly display on the client.

database/realm/RealmDatabaseManager.py, database/realm/RealmModels.py, etc/databases/realm/updates/updates.sql, game/world/WorldLoader.py, game/world/WorldSessionStateHandler.py, game/world/managers/objects/player/ChatManager.py, game/world/managers/objects/player/GroupManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/player/guild/GuildManager.py, game/world/opcode_handling/handlers/guild/GuildCreateHandler.py, game/world/opcode_handling/handlers/guild/GuildDemoteHandler.py, game/world/opcode_handling/handlers/guild/GuildDisbandHandler.py, game/world/opcode_handling/handlers/guild/GuildInfoHandler.py, game/world/opcode_handling/handlers/guild/GuildInviteAcceptHandler.py, game/world/opcode_handling/handlers/guild/GuildInviteDeclineHandler.py, game/world/opcode_handling/handlers/guild/GuildInviteHandler.py, game/world/opcode_handling/handlers/guild/GuildLeaderHandler.py, game/world/opcode_handling/handlers/guild/GuildLeaveHandler.py, game/world/opcode_handling/handlers/guild/GuildMOTDHandler.py, game/world/opcode_handling/handlers/guild/GuildPromoteHandler.py, game/world/opcode_handling/handlers/guild/GuildQueryHandler.py, game/world/opcode_handling/handlers/guild/GuildRemoveMemberHandler.py, game/world/opcode_handling/handlers/guild/GuildRosterHandler.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py, game/world/opcode_handling/handlers/social/WhoHandler.py
+ Guild persistance.
- Drop leader_guid column, leader already exist over guild_members table.
* Modify all Guild handlers to not expect an online player for guild related actions. (Can kick offline player, promote, demote, etc)
* Make player_mgr and session O(1) accessible by guid/name over WorldSessionStateHandler.
=> Guild persistence and other changes.

database/realm/RealmDatabaseManager.py, game/world/managers/objects/player/QuestManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/quest/QuestGiverChooseRewardHandler.py, game/world/opcode_handling/handlers/quest/QuestGiverCompleteQuestHandler.py, game/world/opcode_handling/handlers/quest/QuestGiverRemoveQuestHandler.py, utils/Formulas.py, utils/constants/ObjectCodes.py
- add character_update_quest to RealmDatabaseManager
- used to set quest to DONE
- add done_quests dict to QuestManager
- populate done quests when the player enters the world
- don't let done quests affect the quest giver status
- name consistency
- quest_giver_guid
- methods called from handlers start with handle_
- handle_add_quest
- handle_choose_reward
- handle_complete_quest
- handle_remove_quest
- the quest menu stuff not done yet
- omit done quests from the quest giver menu
- go right to the rewards menu if the quest giver menu has a single quest, and its REWARD status
- check quest requirements checks that a quest is done rather than just accepted
- handle quest complete
- send_quest_giver_offer_reward()
- handle_complete_quest()
- is_quest_complete()
- only instant complete …
=> quest improvements

database/dbc/DbcDatabaseManager.py, database/dbc/DbcModels.py, database/realm/RealmDatabaseManager.py, database/realm/RealmModels.py, etc/databases/realm/updates/updates.sql, etc/databases/realm/updates/updates.txt, game/world/WorldLoader.py, game/world/managers/objects/UnitManager.py, game/world/managers/objects/player/FactionManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/player/ReputationManager.py, game/world/managers/objects/player/SkillManager.py, game/world/managers/objects/player/proficiencies/proficiency.py, game/world/opcode_handling/handlers/interface/CharCreateHandler.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py, utils/constants/ObjectCodes.py
* Initialize factions, according to DBC data, there are only 4 visible reputations or 4 reputations which standing can change:
- Bloodsail Buccaneers (Hostile)
- Booty Bay (Neutral)
- Gelkis (Unfriendly)
- Magram (Unfriendly)
/ Other alliance or horde cities were apparently not handled yet.
* Persist initial reputations on db
* Calculate and send player proficiencies upon login based on DBC data. (Still need to figure how to link rank based proficiencies to the actual skill, e.g. Fishing)
* Move allegiance_status_checker out from UnitManager into FactionManager
=> Initial work on FactionManager/Reputations and Proficiencies.

game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/npc/ListInventoryHandler.py, game/world/opcode_handling/handlers/player/cheats/LevelCheatHandler.py, game/world/opcode_handling/handlers/player/cheats/LevelUpCheatHandler.py, game/world/opcode_handling/handlers/player/cheats/MoneyCheatHandler.py
In the built-in console, GM only commands:
money [x-amt]
level [x-level]
levelup
Fixed bug when right-clicking on vendors while out of range. The client seems to check distance, but the server was not, causing the vendor bag noise to play.
=> More cheat handlers and vendor bug fix

game/world/managers/objects/creature/CreatureManager.py, game/world/managers/objects/player/GroupManager.py, game/world/managers/objects/player/InventoryManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/player/quest/ActiveQuest.py, game/world/managers/objects/player/quest/QuestManager.py
/ Make give_xp() notification skippable, some scenarios like completing quests, will make the client announce given XP, this fixes a visible glitch in which two XP notifications overlapped.
=> * Remove quest db items if the player destroy them.

game/world/managers/objects/player/GroupManager.py, game/world/managers/objects/player/PlayerManager.py
/ Fixed missing loot money notification while on group and split not possible.
=> * Use MSG_SPLIT_MONEY while on group.

database/world/WorldDatabaseManager.py, game/world/WorldLoader.py, game/world/managers/objects/GameObjectManager.py, game/world/managers/objects/LootManager.py, game/world/managers/objects/creature/CreatureLootManager.py, game/world/managers/objects/gameobjects/GameObjectLootManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/opcode_handling/handlers/spell/CastSpellHandler.py
* Modified some loot related methods to be 'generic' to world_obj
* Player, had to add 'current_loot_selection', since gameobject interaction does not set 'current_selection' field, maybe we should be setting it on SpellManager after resolving a single target.
* Known issues:
/ Chest despawn/respawn? Fill loot table upon respawn, right now it will be filled everytime its empty.
/ @Fluglow , left you a comment over CastSpellHandler related to target resolving.
=> * Some work on chests.

game/world/managers/objects/spell/AppliedAura.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, utils/constants/UnitCodes.py
- Separate aura-related classes
- Implement learn_spell spelleffect and health cost handling for spells (Life Tap etc.)
- Add empty handler for Word of Recall Other. The ImplicitTarget is only used for this spell, so it's tough to know what the intended targeting was. Left it empty as it's unlikely players should be able to teleport each other without confirmation.
=> Minor spell/aura related refactoring and fixes

game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CooldownEntry.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellManager.py
- Fix delayed cooldowns (stealth, shapeshifts etc.) starting on aura removal.
- Remove check that made TARGET_INITIAL always resolve to no targets (leftover from the target being always resolved to nothing).
=> Proper handling for delayed cooldowns, fix to TARGET_INITIAL resolving

etc/databases/realm/updates/updates.sql
The explicit database name in the alter command would cause the update script to crash in the case where the database has been named something different from the `alpha_realm`.
=> Removed database name from alter command

game/world/managers/objects/player/guild/GuildManager.py, game/world/opcode_handling/handlers/guild/GuildLeaveHandler.py, game/world/opcode_handling/handlers/guild/GuildRemoveMemberHandler.py
/ Guild master should now be able to use /gquit if there are no members left.
/ Proper error message if /gquit is used by GM and Guild has members.
/ Officers can't kick another officer or the GM.
/ GM can't self kick.
=> Guild handlers fixes noticed by Yushe.

docker-compose.yml
This will prevent the docker containers to automatically start and boot up when rebooting the host machine even after explicitly stopping the docker containers.
=> Restart docker containers on failure only

game/world/managers/objects/player/PlayerManager.py
Changes:
- Appropriately count the difference between the starting level and the final level when setting it up with the gm command `.level` giving and taking away the respective talent and skill point for each level added/removed
- If the exp gained will overshoot the bar multiple times it will count and award the appropriate number of levels
=> Manage multiple level ups and level downs

game/world/managers/objects/timers/MirrorTimer.py
/ Client timer should now remain visible until the bar is fully filled.
=>  Fix MirrorTimer

game/world/managers/objects/spell/AuraManager.py
Fixes crashing on ground-targeted casts when certain auras are applied.
=> Ignore heartbeat proc flag

game/world/managers/maps/MapManager.py, game/world/managers/maps/MapTile.py
/ Tile information remains as None untill the constructor finishes and returns an object, so in some scenarios where multiple entities would require the same tile, loading would trigger more than once. To avoid this, move map processing ouf of the ctor.
=> Change MapTile loading.

game/world/managers/maps/GridManager.py, game/world/managers/objects/player/PlayerManager.py
/ This changes reduce crashes upon players simultaneous login/teleport/entering a new map cell.
/ Fixes a bug in which players could not see other players due to missing update packets. https://i.ibb.co/R9BKjSy/unknown.png
/ Do not trigger tile loading and active cell events if the cell was already active.
/ Player should now retrieve surrounding update packets and then notify self to its surroundings when entering a new cell.
/ Make sure both updates, including tile loading happens before setting a cell as active in order to avoid creatures thread updates.
/ Remove teleport player update, MapManager.update_object(player) should automatically trigger the above actions if the current cell changed.
=> Changes to player update system.

game/world/WorldLoader.py, game/world/managers/maps/GridManager.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/player/PlayerManager.py
/ GridManager will now automatically notify players when they need to update their surroundings in order to create new world objects or destroy them.
/ Actual teleport action is now triggered within the player update thread and when the player has no dirty pending fields. (This fixes a silent client crash).
/ Object creation/destruction will now properly trigger each time a known objects goes out of player scope  (Active cell + adjacents), also if the GridManager changed we will now also destroy self from the old location.
/ PlayerMgr update_lock is now only set from a teleport action.
/ PlayerMgr 'dirtines' will no longer call MapManager.update().
/ Known issue: Creatures wandering between active/non active cell edges will continuously trigger create/destroy packets.
=> Changes to teleport and update system.

game/world/managers/maps/GridManager.py, game/world/managers/objects/player/PlayerManager.py
/ Simplify GridManager update_object()
/ Fix destroy packet bug when directly calling remove_object. (Logout did not properly destroy the player)
/ Fix update bug when moving between cells in the same GridManager but cells did not see each other. (Using relocate teleport)
=> More changes to GridManager.

game/world/managers/objects/player/PlayerManager.py
/ Remove the player from MapManager (Destroy self to surrounding players) before updating party members status.
=> Fix party 'offline' display.

etc/databases/world/updates/ironforge_fix.sql
-- #                                             Ironforge 0.5.3 Fix                                               
-- #  What I've done :                                                                                             
-- #       - Spawn fix NPCs with screenshots from Archives                                                         
-- #       - Spawn fix NPCs in their respective houses (mining, enchanting, rogue...)                              
-- #       - Ignored Ironforge NPCs 6000+ entries                                                                  
-- #       - Ignores 4 guards who wheres in houses or in walls                                                     
-- #       - Ignored all chairs and braziers who were not part of 0.5.3 …
=> ironforge 0.5.3 fix

game/world/managers/objects/MovementManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/player/TaxiManager.py, game/world/opcode_handling/handlers/interface/CharCreateHandler.py, game/world/opcode_handling/handlers/npc/ActivateTaxiHandler.py
/ Players should now be able to see other players flying on taxis even if they were not near that player when the taxi was triggered.
/ Flight state is now persisted and will continue if the player exits or the client crashes.
/ Fixed bug in which taxi mount display remained visible to surrounding players after arriving at the destination node.
/ Players will now also retrieve partial movement packets that were triggered by creatures before the player entered their active cell.
=> Taxi & Movement packets fixes.

game/world/managers/maps/GridManager.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/units/MovementManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py
* Refactor Respawn/Despawn.
* Make sure creatures stop pending wandering movements as soon as they receive any damanage.
* Fixes melee combat unable to start when a creature was moving due bad server side calculation.
(Shane cubes represent the server side guessed position)
Position Bug:
https://streamable.com/5ge9rj
Fixed:
https://streamable.com/522ctg
=> Fix server side creatures movement position calculation (Melee bug) & refactor.

game/world/managers/objects/units/creature/CreatureManager.py
This fixes creatures no longer attacking if you moved to their back without triggering a new move packet (chase).
=> Fix Melee creature orientation bug.

game/world/managers/objects/units/creature/CreatureManager.py
/ Dead creatures over Campfires should no longer 'keep dying' and generating infinite loot while still receiving spell damage.
=> Fix creatures infinite dying bug.

game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/PlayerManager.py, utils/Formulas.py
Formula :  Rage Gained = (Damage Taken) / (Rage Conversion at Your Level) * 2.5 
Generate rage on received damage when units have def/battle stance or bear form
(Berserker stance does not generate rage in 0.5.3)
Move rage logic from PlayerMgr to UnitMgr so all units can use rage
=> Rage generation on received damage

game/world/managers/objects/ObjectManager.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py
/ This continues PR #289 by Flug.
/ Aura fields cannot be written like we do with other fields for updates. The client see this as if the aura was applied again even if value did not change for a given field.
/ Player AuraFields will be written once again after teleports, else, the aura does not show up in the UI even if its active.
/ Players will retrieve all AuraFields upon meeting a new unit, after that, they will only update those fields from other units on partial updates if they were really dirty (Changed values)
/ Tested this with players not creatures.
=> Aura updates.

etc/databases/world/updates/updates.sql, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/ai/BasicCreatureAI.py, game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/quest/QuestManager.py, utils/constants/UnitCodes.py
/ Creatures will now use their known_players collection and avoid get surrounding calls.
/ Invalid Faction 1094 -> 32 (Beast)
/ Send AI reaction state hostile upon aggro.
/ Gameobjects - Do not update traps nor fishing nodes if they have no observers. (Cell still active but no players)
/ Creatures - Do not wander if no observers.
/ Combat - If leave_combat has force flag set, also force current unit attackers to leave combat as well.
/ Quests - use known_objects for update_surrounding_quest_status() calls.
/ Player - Destroy all current known objects to player upon logout and remove self from objects known_players dictionaries.
=> Improve proximity aggro.

game/world/managers/objects/ai/BasicCreatureAI.py, game/world/managers/objects/ai/PetAI.py, game/world/managers/objects/gameobjects/FishingNodeManager.py, game/world/managers/objects/gameobjects/GameObjectLootManager.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/loot/LootMapper.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/player/PlayerManager.py
/ ThreatManager - Creatures should no longer keep looking for players and trying to aggro them while dead or not spawned.
/ ThreatManager - All attack starts should now be triggered by ThreatManager.
/ ThreatManager - Damage 0 (Miss, Block, etc) should now trigger aggro.
/ ThreatManager - attack_update will only call attack() if ThreatManager finds a target and unit is not already in combat with that target (This includes target switch because of threat) and will call leave_combat when 0 targets are resolved.
/ ThreatManager - Negative auras will now also use ThreatManager.
/ ProximityAggro - Players will not notify movement to dead or not spawned units.
/ Creatures/GO's - Avoid update calls if the object has not fishined lazy initialization.
=> / Threat changes and others.

game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/managers/objects/units/player/trade/ProposedEnchantment.py, game/world/managers/objects/units/player/trade/TradeData.py, game/world/opcode_handling/handlers/trade/AcceptTradeHandler.py, utils/constants/SpellCodes.py
* Simplify fishing and enchanting implementations.
* Restrict enchanting skill gain to profession spells.
* TODO: Skill gain is currently guaranteed for all enchants regardless of skill level.
* Fix minor edge case for GO casters.
=> Fishing and enchanting refactoring

game/world/managers/objects/locks/LockManager.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/DuelManager.py, game/world/managers/objects/units/player/EnchantmentManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/managers/objects/units/player/StatManager.py
* Add basic handling for spell proc enchants
* Apply weapon damage enchants
* Use correct values for temporary enchant durations and simplify logic
* Simplify enchant aura handling
* Fix handling auras that don't break stealth
* Fix gathering profession failure check
* Move validation logic from spell effect handlers to validate cast
* Most spell validation can and should be done before effect application in `validate_cast`. Validation at effect application can lead to one effect failing with others applying.
=> Enchant procs and damage application, minor bug fixes and spell refactoring

game/world/managers/objects/spell/SpellEffectHandler.py
Check spell attack type in weapon damage handlers. Required for some NPC/druid abilities that don't explicitly define the weapon type used for the attack. Unsure if these checks cover all cases.
=> Weapon damage effect crash fix

etc/databases/world/updates/updates.sql
Resolve part of #319. All screenshots mentioned bellow can be found in Alpha Archives, Teldrassil folder.
- **Bloodfeather** 
Bloodfeather type who miss display_id : Rogue, Mattriach, Wind Witch
We have screenshots that show bunch of Bloodfeathers, all with the same display_id (3021).
We also have a screenshot of a Bloodfeather Sorceress with display_id 3021 (1.12 use another display id for this mob)
In 0.5.3, all Bloodfeathers use the same display id, later blizzard will add color variation probably to help players.
- **Gnarlpine**
Gnarlpine type who miss display_id : Warrior, Defender, Ursa, Gardener, Avenger, Pathfinder
We have some screenshots that shows  Gnarlpine (Ambuser, shaman and also a named), all with the same display_id (brown gnarlpine)
Same as Bloodfeathers, in 0.5.3 all …
=> Teldrassil improvements

game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/managers/objects/units/player/StatManager.py, game/world/managers/objects/units/player/trade/TradeData.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py
* Add checks for player skill and required skill for profession crafts. Closes #357
* Fix profession skills going over their maximum level
* Learn profession skills when learning the related spell
* Add correct handling for profession skill max values
* Max profession level now depends on the learned spell (Apprentice/Journeyman/Expert)
* Use base skill value for gathering skill gain
* Simplify/rename some skill-related methods
=> Crafting profession skill gain restrictions and correct max skill levels

etc/databases/world/updates/updates.sql
* Queried and adjusted damage spells only (Effect ID 2, only checking Effect_1).
* Spells with other effects may still be too powerful, but the most noticeable issues should be gone.
* Not all changed spells have been tested, but characteristics such as effects, descriptions and spell names have been checked to match.
* Can provide full queries/other data if someone is interested in continuing this work for other types of creature spells.
* closes #369, closes #374.
(Disgusting) query for searching the described spells. Change the spell id in `sp.id = cs.spellid_1` to compare against other creature spell entry spells.
`[alpha_world]> select ct.entry, ct.spell_list_id, ct.name, ct.level_min, sp.SpellLevel, cs.spellid_1, cs.spellid_2, cs.spellid_3, sp.name_enus, sp.namesubtext_enus, …
=> Adjust creature spell ranks for damage spells to match caster level

etc/databases/world/updates/updates.sql
Ashenvale
========
**Foulweald**
There are 2 possible models (except ear variation and the named) :  Blue or Brown
Vanilla Foolweald use blue model: 
So I used blue models for Foulweald mobs, the exact same as vanilla (including ear variation)
**Thistlefur**
Same as Foulweald, there are 2 possible models.
Vanilla Thistlefur use Brown models and white one (not part of 0.5.3)
So I used brown models for Thistlefur,  I replaced white one with brown model.
**Xavian & Felmusk**
Satyr models with a lot of color variations are already present in 0.5.3
I used exact same models than 1.12 for each mobs.
**Dark Strand**
Dark strand mobs use 3 different models for each mobs, I updated each Dark Strand mob to remove unavailable display id and add those screenshots show.
**Wrathtail**
There is only one …
=> Ashenvale Improvements

game/world/managers/objects/spell/AuraEffectHandler.py
Fixes crash on login when a player has learned a spell that uses the aforementioned effect.
=> Add separate handler for SPELL_AURA_MOD_INCREASE_MOUNTED_SPEED

game/world/managers/objects/spell/AppliedAura.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/PetManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/PlayerManager.py
* Apply shapeshift-restricted passives on shapeshift change. Closes #385 
* Shapeshift passives aren't linked in the database. It's likely that they were taught with the forms via a quest. 
* Bear form passive is taught by "Strength of the Bear" (1938), Cat Form passive by "Feline Quickness" (3031).
* Add level restriction to pet taming.
* Implement tamed pet experience gain.
=> Shapeshift and pet fixes

etc/databases/world/updates/updates.sql
Duskwood
========
About
----
In this area, a lot of npc/mobs have a really low entry (approx 200-800).
It appears that Duskwood will be updated in 0.5.4, and lot of npc/mobs will get new models.
In 0.5.3, most of them still have very old models.
Barkeep Hann
-----
Madame Eva
-----
See target frame
Commandant Althea Ebonlocke 
-----
Very difficult to be sure just with this screenshot, here's more evidences
This display id seems placeholder for important female NPC, like Grand Admiral Jes Teres in SW
We can see here that Madame Eva and Commandant Althea have linked display_id and entry which reinforce this assumption.
Morg Gnarltree
----
On same screenshot
We can barely see a NPC, he seems to wear a black belt and black wrist. His entry and display_id make sens : Entry 226, display_id : …
=> Duskwood Improvements

game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/units/PetManager.py, game/world/managers/objects/units/player/PlayerManager.py
* Restrict and update pet spells by their current level. Closes #397.
* This is temporary behavior; pets should be taught the spells instead.
* Match summoned warlock pet level to the summoner's level. 
* Keep hunter pet level the same on tame and resummon.
* This doesn't persist through relogs/restarts (#281).
* Add TODOs in PetManager on some existing issues.
=> Pet level handling improvements

etc/databases/world/updates/updates.sql
Darkshore
======
About
------
Here's a screenshot of linked display_id from Darkshore, this means that most of the models we want to find are probably close to this range.
Moonstalkers
------
We retrieve them close to display_id range
We can see different scale for each models
So we replace display_id taking into account the level range for the scale.
Bears
----
There are 3 types of bears. We retrieve them close to display_id range
We can see different scale for each models
So we replace display_id taking into account the level range for the scale.
Blackwood
-----
There 3 models available, we retrieve them close to display_id range
The last model has 1.5 scale, probably for a named.
Basically, Bloodwood Pathfinder is the only use brown model, all others should use black one.
Later, …
=> Darkshore improvements

etc/databases/world/updates/updates.sql
Silverpine
=======
About
-----
Here's a sample of Silverpine linked display_id, the whole range is very wide on this area.
We can probably see here : Rot hide mobs, Raging Rot hide, Elder lake skulker, Lake Skulker, murloc mobs
Moonrage Whitscalp
---
He is the weakest mob of Moonrage, we choose display_id 729 with 0.9 scale.
Lake Skulker
----
There are 2 mobs : Lake Skulker, Elder Lake Skulker. 
Elder Lake skulker miss his display_id.
We sure of these display_id cause Lake Skulker use 863. But on screenshot, he is small.
Probably, on 0.5.3, Lake Skulker use 862, and Elder Lake Skulker use 863.
Later, blizzard will update Elder and for some reason, Lake skulker will take 863 display_id ?
It's make sense but maybe we need to wait for more evidences ?
I choose 862 for lake skulker, and 863 …
=> Silverpine improvements

etc/databases/world/updates/updates.sql
Hillsbrad
======
Naga
-----
There is only one model in the whole set and no female. We apply display_id 4036 on all hillsbrad nagas.
Hillbrad Sentry
----
We remove unavailable display_id 2 3 4
Mudsnout Gnoll
----
Here's all possible models
We can see like a crowd on 493, 603, 662. We cant see it on target frame. We eliminate them.
So remaining choice are 275 & 494.
The other gnoll here (Mudsnout shaman) use 662 with scale 1.13, he is highest level than Mudsnout Gnoll.
So we choose display_id 275 with 1.0 scale.
Melisara
-----
We choose display_id 915 with 1.0 scale
=> Hillsbrad improvements

etc/databases/world/updates/updates.sql
Wetlands
======
Captain Stoutfist
----
Dragonmaw
-----
There is only one model : display_id 1139
We change  display_id of all these guys with 1139
Should we include the named 2091 Chef Nek'rosh ?
Whelp
-----
There are only 2 red whelp model on the whole set.
We change display_id of Red Whelp/Flamesnorthing Whelp with display_id 956
Wyrm
----
All red wyrms models
We apply right display_id in taking account of level range. We also use 1.5, it's make sense, some of these mobs are 60+
Ooze
----
All ooze models
We choose red one 681 for Crimson Ooze with 1.3 scale. 
We can see on screenshot that Monstrous ooze is a bigger than Crimson ooze, so we choose 682 with 1.5 scale
Bart Tidewater
----
This guy probably should use captain placeholder (there is only one color for 0.5.3)
Vanilla model here
=> Wetlands improvements

etc/databases/world/updates/updates.sql
Arathi
=====
Highland Strider
----------
We use 0.8 scale that seems to fit the most with screenshot, display_id 961
Young Mesa buzzard
-------
He is the weakest buzzard in arathi. Here's other models used in arathi.
Probably, in 0.5.3 he should use same as Mesa Buzzard, and that's probably why blizzard will update it later, but no evidences here.
To respect scale by level, we try to find another same model with a lower scale.
We use display_id 388 with 1.1 scale. 
Foulbelly
-------
Arathi stormgard ogre push
Since he is a named, we use model with the highest scale for this mob
Probably, the other named in this area  Or'Kalar should use one of these display_id (1124 ?), but no clear evidences yet.
Ruul Onestone
-----
There is only one model with a white bag : 1046. He is part of ogres we …
=> Arathi improvements

etc/databases/world/updates/updates.sql
**### Fix #454** 
Binders
======
Dolthar loch modan
--------
Zoom in, this guy is bald with a read beard.
Myiela dolanaar
-------
if 3777 is binder of Aldrassil and 3779 is binder of Darnassus, then 3778 is binder of Dolanaar
Gryphon
====
Thorgrum
-----
=> Loch Modan/Dolanaar binders & Loch Modan Gryphon master fix

game/world/managers/objects/spell/AppliedAura.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/player/EnchantmentManager.py, game/world/managers/objects/units/player/InventoryManager.py, game/world/managers/objects/units/player/StatManager.py, utils/constants/SpellCodes.py
* Add missing target type for "Zone Recall (OLD)". Unhandled as the purpose of the spell is unclear.
* Add checks to aura stat modifier removal (crash fix)
* Fix edge cases with binding and enchants on equip
* Fix creature type check for spells (closes #435, closes #436, closes #437)
* Implement damage shield auras (closes #417, closes #445)
* Add basic chain damage handling (cleave/chain lightning etc.)
* Implement attack speed modifiers
* Fix self-cast finishing spells (Slice and Dice)
* Fix cast/aura duration for finishing spells
=> Spell-related fixes

etc/databases/world/updates/updates.sql
STV
===
Gyll
----
Corporal Kaleb
----
Basilisk
----
Since Stranglethorn is an early zone, basilisk should be present at begining of display_id set.
Here's what we find
All those are way too big, the only one at begining of the set and with a normal scale is 601 (used by another basilisk here). we choose 601 for  Cold eye & trashtrail basilisk.
Gorlash & Mokrash
----
Naga
----
All nagas should use 4036, we apply it on Naga explorer, Zanzil naga, Lord Sakrasis
Raptor
----
We miss display_id of Jungle stlaker and Thetis, we have no infos about it. On area, there is Young Jungle stalker with a display_id
This display_id 615 is way too big scaled for Young Jungle Stalker.
Probably, Jungle Stlaker and Thethis will use same colors as Young Jungle Stalker. We cant be sure about colors, there are …
=> Stranglethorn Improvements

game/world/managers/objects/ObjectManager.py, game/world/managers/objects/units/PetManager.py, game/world/managers/objects/units/creature/ThreatManager.py
* Remove `can_attack_target` from ThreatManager and use existing UnitManager method instead
* Fixes issue with pets not being able to attack neutral enemies
* Add player-controlled flag to pets
* Fixes issue with pets not being targetable with some helpful spells
=> Use existing can_attack logic in ThreatManager, correct pet unit flags

etc/databases/world/updates/updates.sql
Tanaris
======
Scorpid
--------
Probably, 3 scorpids type here should use pink model. We use appropriate scale for each level range.
Basilisk
--------
See background, it's probably Gasshide Basilisk
See background, it's probably Gasshide Gazer
Such as scorpids, 3 basilisks type should use same color.
Hazzali (silitidh)
-------
We will use those 3 models
Ogre
------
Probably tanaris ogre push
There are 5 models for 5 mobs type (2casters, 3melee), we use appopriate scale for each level.
Buzzard
--------
There are not a lot red buzzard model (probably 2 with one with a tiny scale).
There is 3 types of buzzards here. We use same model for all. 
Buzzard Roc here already use this display_id.
Dune Smasher
----------
Only one color for giant in 0.5.3, we use default one
Thistlerub Rootshaper …
=> Tanaris improvements

etc/databases/world/updates/updates.sql
Burning Blade
=======
We change all display_id of Burning Blade orc with 1139 placeholder. We exclude Burning blade Nightmare (horse), and high entries whose are not part of 0.5.3.
Here's evidences
Desolace
======
Centaurs
-----
We fix forgotten Magram Marauder and Magram Outrunner in Desolace
Rabid Bonepaw
----
By mistake, I applied display_id on 4890 (Piter Verence)  instead of 4690 (Rabid). So we revert Piter display_id and apply it on rabid
=> Burning blade mobs fix & Desolace fix

etc/databases/world/updates/updates.sql
Feralas
======
About
-------
Bad news is that we don't have any screenshot from 0.5.3, good news is we have a very clear range for this location
We can see almost all mobs of this area.
Frayfeather
-----
We use appropriate scale for each lvl range
Hulking
------
2 mobs miss display_id, others here already use brown models, so we put silver for those. We use appropriate scale for each lvl range
Gordunni 
-----
We use appropriate scale for each lvl range
Woodpaw
-----
We use appropriate scale for each lvl range
Jademir
-----
We use appropriate scale for each lvl range
Northspring
----
2 mobs miss display_id, we can see only one model in range, it's unsure but we apply it on Roguefeather/Harpy for now.
Giants
----
Only one colors in 0.5.3
Elementals
----
We put placeholder display_id 110 for …
=> Feralas Improvements

etc/databases/world/updates/updates.sql
Dustwallow
========
Murlocs
-------
As we can see, there are all violets. Most of them already use the right display_id, we apply the same on others.
Horde Village
--------
We spawn 2 trainers and we change Ogre NPC display_id to the same trainers use. We also change Nazeer (orc) display_id with 1139 placeholder (like Gromgol).
Turtle
-----
Only one colors for 0.5.3, we use 2 differents scale (1 & 1.2) for 2 turtles types here.
Firemane
-----
There is no female models for those mobs, most of them already use correct display_id, we apply it on those whose miss it.
Misc
-----
Giant Darkfang spider miss his display_id, we choose same models as Darkfang spider, but with a bigger scale.
Acidic Swamp ooze miss his display_id, we use same as vanilla.
=> Dustwallow improvements

etc/databases/world/updates/updates.sql
Badlands
======
Ogre
-----
Some ogres here already use models above, we replace those missing their display_id with models above (+ a caster model)
Anathemus
-------
He's a giant and we have only one color in 0.5.3
Starving Buzard
-------
Giant buzzard use the bigger, we use the other.
Wargolem
-----
Since we have no evidences, we use same as vanilla one
Earth Elementals
-----
We apply earth elemental placeholder for some of them missing their display_id
Galek
-----
On vanilla, Galek look like this
We have no blood elf male model, but look here
It's seems that NE male model is placeholder for blood elf model (same cloth, linked with female blood elf)
We use NE male for Garek
Shadowforge
--------
(NO MODIFICATIONS DONE)
Which models shadowforge (dwarves near Maraudon) should use ?
Dark …
=> Badlands improvements

etc/databases/world/updates/updates.sql
West Plagueland
============
High Priest Thel'danis
----
Skeletal
----
There is no "only bones" models, so we use Skeletal placeholder with 1.0 scale  for all of them whose missing display_id.
Ooze
----
Devoring ooze miss display_id
Ooze next to Devoring Ooze use 681, so we use 682 (it's also same color as vanilla)
Putridus
----
There is only one color for 0.5.3, we use 1.2 scale
Misc
-----
Since models are already presents in 0.5.3, we will use same models as vanilla for them
4474 Rotting Cadaver
4475 Blighted Zombie 
1802 Hungering Wraith
1804 Wailing Death (as we saw in Ashenvale, I choose Banshee, but it's also can be Ghost)
1912 Rotting Behemoth
1794 Soulless Ghoul
=> West Plague Improvements

database/dbc/DbcDatabaseManager.py, database/dbc/DbcModels.py, etc/databases/dbc/updates/updates.sql, game/world/managers/objects/gameobjects/GameObjectBuilder.py, game/world/managers/objects/locks/LockManager.py, game/world/managers/objects/spell/CooldownEntry.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/utils/TrainerUtils.py, game/world/managers/objects/units/player/DuelManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/managers/objects/units/player/StatManager.py, game/world/managers/objects/units/player/TalentManager.py, game/world/managers/objects/units/player/guild/PetitionManager.py, game/world/opcode_handling/handlers/friends/FriendAddHandler.py, game/world/opcode_handling/handlers/friends/FriendDeleteHandler.py, game/world/opcode_handling/handlers/friends/FriendDeleteIgnoreHandler.py, game/world/opcode_handling/handlers/friends/FriendIgnoreHandler.py, game/world/opcode_handling/handlers/gameobject/GameObjectQueryHandler.py, game/world/opcode_handling/handlers/interface/CharCreateHandler.py, game/world/opcode_handling/handlers/inventory/ItemQueryMultipleHandler.py, game/world/opcode_handling/handlers/inventory/OpenItemHandler.py, game/world/opcode_handling/handlers/npc/CreatureQueryHandler.py, game/world/opcode_handling/handlers/npc/TrainerBuySpellHandler.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py, game/world/opcode_handling/handlers/player/cheats/CooldownCheatHandler.py
- Deprecate custom_PrecededBySpell column.
- Deprecated use of spell_chain.
- Honor client dbc data when filling training lists packets.
- Send and validate required skill, min rank and step.
- Initialize talent related skills on all characters upon creation.
- Trainers code decoupling.
- Spells that are preceded by another spell will now trigger SMSG_SUPERCEDED_SPELL. (Some spells allow for holding multiple ranks, others do not and must be removed upon learning a new rank)
- Counterspell now properly works. (On players)
- Fixes crash with SPELL_EFFECT_INTERRUPT_CAST.
=> Trainers & Others.

database/world/WorldModels.py, etc/databases/dbc/updates/updates.sql, etc/databases/world/updates/updates.sql
- Drop the `applied_updates` table when creating a new DBC database.
- Fix to allow recreation of DBC database without first dropping it.
- Rename `gameobject_involvedrelation` to `gameobject_quest_finisher`
- Rename `gameobject_questrelation` to `gameobject_quest_starter`
- Rename `areatrigger_involvedrelation` to `areatrigger_quest_relation`
- Updated python models to reflect database changes
=> General database improvements #638 #639 #642

game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/units/UnitManager.py
/ Do not check for melee enchantments procs if the victim died on that hit. 
/ Do not execute melee extra attacks if the victim died on that hit. 
/ Skip spell damage if triggered on a dead target.
=> Minor fixes.

etc/databases/world/updates/updates.sql
NPC FIX
===
#673
#672
#634
#607
#598
#597
#592
#591
#582 (PART OF, Strumner/Celmoridan pet spawned)
#581
Also spawned Farmountain NPCs (Cartography, Survival)
Thanks @devw4r
=> Npc display_id and spawn fix

game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AppliedAura.py
* Fix possible player/creature aura duration update race condition for periodic active (channeled/AoE) spells
* Hopefully addresses #696; I couldn't reproduce the issue locally
* Fix interrupt handling for active spells without a cast time (Addresses comment in #696 @GrenderG)
* Refactor invalid cast animation fix
=> Spell fixes / refactoring

database/dbc/DbcDatabaseManager.py, tools/ClassTrainersSkillsGenerator.py
* Treat 'exclude' fields in `SkillLineAbility` as reversing flags instead of masks
* `ExcludeRace` is always 0, but `ExcludeClass` is set for some entries (table below)
```
+----------------+-----------+--------------+-----------------------+
| SkillLine      | ClassMask | ExcludeClass | Spell                 |
+----------------+-----------+--------------+-----------------------+
| Lockpicking    |       136 |            1 | Pick Lock             |
| Weapon Talents |      1090 |            1 | Dagger Mastery        |
| Weapon Talents |      1090 |            1 | Dagger Power          |
| Weapon Talents |         0 |            1 | Mace Specialization   |
| Weapon Talents |        80 |            1 | Mace Finesse          |
| Weapon Talents |      1090 |            1 | Dagger …
```
=> Correct skill line ability exclusion logic

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/dynamic/DynamicObjectManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AppliedAura.py, game/world/managers/objects/spell/aura/AreaAuraHolder.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/DuelManager.py
* Add `AreaAuraHolder` for updating area auras.
* Separate other channeled spells' handling from area auras (handled by target's AuraManager now).
* Area aura effects now work solely off the caster's SpellManager update. This should fix inconsistencies caused by race conditions with channeled periodic effects (closes #736, #696 probably related).
* Minor changes to dynamic object handling
* Move spell target power type to `validate_cast` from AI cast checks (closes #737)
* Add quick fix for threat not clearing after duels
=> Implement area aura effects separately from aura handling / minor fixes

game/world/managers/CommandManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AreaAuraHolder.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/player/EnchantmentManager.py
* Fix power type check for creatures without a power (closes #737)
* Fix mana leech handler behavior when leech amount is greater than remaining mana
* Restrict aura removal calls' scope to avoid removing unrelated auras
* Add source restriction when removing by spell ID where applicable
* Remove auras by source spell when possible
=> Power type validation/mana leech/aura removal fixes

game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/GroupManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py
* Refactor power regeneration code and move most constants to `StatManager`
* Merge power-related methods to remove duplicate logic
* Use offsets by power type id where possible
* Regeneration and power tick methods are separate to simplify regen logic to one power/call
* `StatManager` holds all regen/decay constants and stores them as per 5.
* Energy regen is slightly nerfed to achieve even values with /5 calculations (5 energy->4 / 2sec)
* Change how mana generation behaves
* Mana regenerates 1% base mana every tick
* Actively casting and finishing casts interrupts additional spirit-based mana regeneration for 5 seconds
* Closes #415
* Decrease Cat Form attack speed from 1.0 to 2.5 (bear form).
* A guess based on Cat Form giving a haste buff, and feral energy starving quickly with such …
=> Fixes and major refactor for power regeneration, other stat fixes/balancing

game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AreaAuraHolder.py, game/world/managers/objects/spell/aura/AuraManager.py
* Fix area aura cancellation
* Fix area aura collision/cancel handling
* Fix aura removal when applying multiple ranks of the same (harmful) spell (closes #757)
* Fix validation when attempting to cast a buff when a higher rank is already applied
* Simplify logic in `remove_colliding_effects`
=> Aura collision/override and area aura bug fixes

database/realm/RealmDatabaseManager.py, etc/config/config.yml.dist, utils/ConfigManager.py
QOL improvement: added ability for GM accounts to be auto created via a config option, disabled by default.
=> QOL: Add ability for gm accounts to be auto created

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/aura/AppliedAura.py, game/world/managers/objects/spell/aura/AuraEffectDummyHandler.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/PetManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py
* Implement infinite periodic aura handling
* Addresses first part of #805. Cooldown reset should happen through `PetManager` once totem logic is added.
* Fix party member targeting for pet spell casts
* Fix bug with harmful auras being resolved as helpful 🤭 
* Closes #811, closes #800
* Correct bonus application for periodic damage effects
* Closes #806, nice catch :^)
* Add initial spells to warlock pets (initial spells are determined by the summon spell's `SpellLevel`)
* Closes #812 
* Add spells to pet action bar automatically  on first summon
=> Various spell/aura/pet bug fixes + refactoring

game/world/managers/objects/spell/SpellManager.py
* Fix cast validation for self-cast, harmful AoE spells (Frost Nova etc.)
* Fix finished casts triggering interrupts on unit death/other `remove_cast` calls
=> Spell interrupt and AoE cast validation fixes

game/world/managers/CommandManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/DamageInfoHolder.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/managers/objects/units/player/StatManager.py
* Add spell miss result handling as described in #238.
* Closes #238, closes #333, closes #544
* Spell miss (resist) formulas are guessed. Alpha does not have partial resists. The used formulas are a mix of partial resist/full resist formulas from VMaNGOS, and use spell-specific skills instead of level.
* TODO: Melee spells should use their corresponding spell skills, but are currently using weapon skill.
* TODO: Spell immunity handling should be refactored to better fit these changes.
* Fix melee hit chance calculation for higher-level targets and adjust related formulas
* Melee combat with lower skill is much less punishing now
* Fix some melee swing spells being instant
* Use melee skill gain formulas for spell skills
* Add a more proper fix for melee spell combat logging
* Fix dual …
=> Spell miss results implementation + other spell-related fixes

etc/databases/world/updates/updates.sql, game/world/managers/objects/units/creature/utils/TrainerUtils.py, game/world/opcode_handling/handlers/npc/TrainerBuySpellHandler.py
- **Fix server disconnect on buying spell.**
- Added full profession trainer template to apprentice trainers for now, instead of nothing.
- Fixed being able to train profession spells outside of your skill due to client bug (closes #858 ability to train, even when spells appear green.)
- Fixed similar train validation issue for talents; talents showing unavailable spells as available after successful train issue still exists.
- Minor improvements to `TrainerUtils.get_training_list_spell_status()`.
=> Profession Trainer Improvements/Bug Fixes

game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/StatManager.py, utils/constants/SpellCodes.py
* Add handling for cast speed modifiers
* Values for spell cast time/channel time now snapshot at the start of the cast
* Improve effect miss results handling
* Skip applying subsequent spell effects if one results in a full miss
* Exclude `SPELL_EFFECT_LEAP` from miss handling (charge can no longer resist)
* Fix some ranged abilities using incorrect miss logic
* Fix spell pushback applying twice on auto attacks (closes #850, closes #569)
* Simplify crit aura mod handling
=> Spell cast speed modifiers / spell-related fixes / refactoring

game/world/managers/maps/MapManager.py, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/PlayerManager.py
* Fix generating targets for proc auras
* Exclude gameobject casts from spell miss logic
* Fix area auras not resolving targets correctly in some cases
* Fix `spell_go` packet miss structure
* Correct `can_attack_target` pvp map check
=> Spell crash/bug fixes

game/world/managers/objects/locks/LockManager.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/opcode_handling/handlers/player/LogoutCancelHandler.py, game/world/opcode_handling/handlers/player/LogoutRequestHandler.py, tools/ClassTrainersSkillsGenerator.py, utils/constants/MiscCodes.py
* Fix applying passive area auras on login / simplify resolving passive targets
* Fix targeting checks for spells with both friendly and hostile implicit targets
* Fix First Aid max skill and skill gain logic
* Fix and refactor loading cast UI on spell learn
* Track aura indices for all unit state/flag changes caused by aura effects (closes #526)
=> Spell targeting, unit status effect and First Aid-related bug fixes

game/world/managers/objects/ai/BasicCreatureAI.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/MovementManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py, utils/constants/SpellCodes.py
* Correct aura interrupt flag for combat actions
* Fix resetting unit auras after evading (related to pathing/Namigator? @devw4r)
* Fix stealthed creatures not detecting players until they've been detected by a player
* Remove all stealth auras on combat actions (https://github.com/The-Alpha-Project/alpha-core/issues/613#issuecomment-1416877496)
* some stealth auras lack proper interrupt flags
* Fix proc spell aura target resolving when changing targets (Arcane Missiles)
* Fix script effects being able to be resisted (Arcane Missiles)
* Fix spell skill check for proc spells
* Triggered spells don't have a skill type (Arcane Missiles Effect, Chilled etc.), track and use source spell skill instead
* Remove unused methods in spell code, group logic in `validate_cast`
* Replace `CastingSpell` …
=> Aura interrupt and spell fixes, spell refactoring

database/realm/RealmModels.py, etc/databases/realm/updates/updates.sql, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/pet/ActivePet.py, game/world/managers/objects/units/pet/PetData.py, game/world/managers/objects/units/pet/PetManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/handlers/interface/CharEnumHandler.py
* Track pet activity state in database
* If a permanent pet is active on logout, display it in character selection and summon it on login.
* Partially addresses #281 
* Don't allow casting a permanent pet summon if a controlled pet is already active
=> Pet active state persistency, summon cast validation fix

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/ai/PetAI.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/pet/PetData.py, game/world/managers/objects/units/pet/PetManager.py, game/world/managers/objects/units/player/PlayerManager.py
* Add support for creatures having pets
* Cast creature pet summon spells on respawn
* Disable chase for creatures with no melee (Imp)
* Fix bug with units not chasing after changing targets
* Modify target selection logic in `PetAI`
* Ignore the pet's own `ThreatManager` 
* Only track pet stay/follow state in `PetAI`, infer attack state from the presence of a combat target
* Always match owner combat target for creature-controlled pets
* Implement pet react and assist behavior when not passive
* Fix interrupt issue with manual pet spell casts
=> Unit PetManager support, pet AI improvements

game/world/managers/objects/script/ScriptHandler.py
Closes #838 
- Restores "Shambling Skeleton" (entry 200) as a basic warrior mob without special abilities (as none are known).
- Changed spawn points for Skeletal Warriors and Mages to shared and also mix in Shambling Skeleton.
- Changes quest "The Night Watch (56) to match the original where it targeted three different enemies - Skeletal Warriors, Mages and Shambling Skeletons - but only 6 of each. Also changed monetary reward to 18s 78c (was 17s).
=> The Night Watch part 1 quest restoration

game/world/managers/objects/script/ScriptHandler.py
This database update despawns trade skill related game objects clearly not present in the alpha:
- Herbs: Dreamfoil, Black Lotus, Golden Sansam, Gromsblood, Plaguebloom, Sungrass and Mountain Silversage
- Ore Veins: Thorium, True Silver
Update: I'll leave the chests alone for now.
=> Despawn GameObjects clearly not present in 0.5.3

game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AppliedAura.py, game/world/managers/objects/units/UnitManager.py
* Fix resolving harmfulness for some creature spells (closes #948)
* Fix resolving passiveness for auras with differing spell target types but same targets (#948)
* Fix spell channel start being sent on a full miss (closes #951)
* Fix melee attack procs only being checked on successful hits (partially addresses #952)
=> Spell bug fixes

etc/databases/world/updates/updates.sql, game/world/managers/objects/spell/ExtendedSpellData.py
Closes #979
Closes #974 
Closes #985 
Closes #987 
Closes #988 
Closes #989 
Closes #994 
- despawn Purple Lotus, this herb was clearly not yet implemented as it has no model, no loot, and isn't pickable
- despawns the herb Arthas's Tears, same as above
- despawns Icecap, same as above
- despawns Blindweed, same as above
- fix Grumnus Steelshaper's trainer_id to blacksmithing
- removes a (floating) campfire from Light's Hope Chapel, EPL. Reasoning: despite its rather low ID its placement is clearly not matching the terrain. It's also not visible on https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Eastern%20Plaguelands/fb9bf0fd401fcbb4.jpg
- sets the faction for the EPL flight master to Human, Alliance. Reasoning: he's hostile to Horde in the …
=> Various fixes and Zone cleanup

etc/databases/world/updates/updates.sql
For some reason this summonable dev only NPC has it's DisplayID set to 0.
The correct DisplayID exists in 0.5.3 and other databases have it corrected.
https://www.wowhead.com/classic/npc=128/angry-programmer-tweedle-dee
https://www.youtube.com/watch?v=op4JHRWl-rk
=> Fix Angry Programmer Tweedle Dee

game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellManager.py
* Implement aura proc handling for spell results
* Add ammo type resolving for creature spell casts
* This should fix ranged attacks not being displayed as described in #952. The client doesn't seem to recognize non-projectile ammo info (thrown/wand) for creature casts, so the issue remains for Throw. It's unclear whether this is a client or server issue.
=> Spell aura proc and creature ranged attack fixes

etc/databases/world/updates/updates.sql
- Despawn unnamed object from Ratchet. Reasoning: no idea what this would have been, didn't even have a name
- Despawn duplicate Fire Totem from Barrens Lift. Reasoning: is a WMO in 0.5.3
- Despawn Highperch Wyvern Egg from Thousand Needles, quest NYI
- Despawn Sunscorched Shell from Thousand Needles, quest NYI
=> Barrens/Thousand Needles fixes

etc/databases/world/updates/updates.sql
- Replace Sack of Corn displayid with placeholder (used dwarven sack of grain)
- Set proper faction for Hazzali and Centipaar insects (they were non-aggressive but should be)
- Despawn unused gameobjects Gahz'ridian and Uldum Pedestal (quests NYI)
- Set proper faction for Dunesmasher (they were non-aggressive but should be)
- Set dwarf placeholder for Prospector Gunstan
Since Gadgetzan is completely unfinished it's much smaller than in vanilla. Several houses are missing or placeholders so these gameobjects which likely bled in from vanilla were laying in the sand:
- Despawn books laying around in the sand (houses missing).
- Despawn stove from future Gadgetzan area (house missing)
- Despawn partially floating benches from future Gadgetzan area (inn missing).
Apart from that there were …
=> Tanaris cleanup

etc/databases/world/updates/updates.sql
- Set placeholder display_id for Wintersbite, Khadgar's Whisker, Firebloom
- Change size for Goldthorn and Firebloom to 0.5
- enable Mithril Deposit to be mined at 155 skill level, reasoning: [here](https://crawler.thealphaproject.eu/mnt/crawler/media/Text/WoWVault/WoWVault-Guidebook.txt), search for "mithril"
- set placeholder display_ids for ogres Glommus, Grel'borg the Miser, Mug'thol. All best guesses as there are very few models to choose from and they all look pretty similar except for the clothing. Have used two-headed ogre for casters as usual.
- Despawn Cauldron, Campfire and 2x Campfire Damage from future Argent Dawn camp in WPL
- Despawn Andorhal Silo Temporal Rift objects, quest NYI
- Set placeholder display_id for Araj the Summoner. There is exactly one "male caster" scourge …
=> DB update Alterac/Hinterlands/WPL/Badlands/Stonetalon

etc/databases/world/updates/updates.sql
- Enable remaining Mithril Deposits/Ooze Covered Mithril Deposit to be mined at 155 skill
- Set placeholder (normal Mithril Deposit) for Ooze Covered Mithril Deposit
- Set placeholder (normal Silver Vein) for Ooze Covered Silver Vein
- Set faction for Silithid to 16 (monster)
- Set display_id for Silithid Ravager (previously unused model of similar color to vanilla)
- Despawn lamppost (duplicate to WMO)
- Despawn Panther Cage (quest NYI)
- Despawn Wanted Poster: Arnak Grimtotem (quest NYI)
=> Thousand Needles cleanup

game/world/managers/objects/spell/aura/AuraEffectDummyHandler.py
[Salt Flats Racer Normal](https://db.thealphaproject.eu/index.php?action=show_spell&filter=salt+flat&sort_order=Name_enUS&max=3&pos=1) is a dummy aura applied by scripts during the Shimmering Flats racing event. It does nothing but leaving it unhandled spams the log and I can't have that.
=> Add Salt Flats Racer Normal dummy aura handling

etc/databases/world/updates/updates.sql
Closes #1085 
Closes #1089 
Closes #1092 
Closes #1093 
Closes #392 
- fix Tursk, Crawler Trainer's name, faction, level and stats. Also have him spawn his pet.
- quest objective text fixes for all quests from Regthar Deathgate because they referred to him as being "west of Crossroads" which he wasn't located at in 0.5.3 (he's in Crossroads at the watchtower). Quest texts from Allakhazam and Goblin Workshop, proof links in the SQL file.
- set placeholder display Id for Kreenig Snarlsnout
- tailoring vendor id to Kil'hala.
- fixes the broken Shadowfang Keep cell doors. They spawn at too low Z so even after opening them you can't pass. Random, I know.
- despawn several objects in the Barrens which are affected by terrain changes - either they float or they make no sense at that position
- …
=> Various fixes

game/world/managers/CommandManager.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/player/SkillManager.py
* Add missing upper bound checks to `set_skill` calls
* Fix skill value usage in skill_step effect handler
* Fix fishing skill gain chance
* Fix updating max skill when learning a profession spell
* Fix crash when teaching spells are cast on invalid targets
=> Skill logic and crash fixes

game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/StatManager.py
Closes #1152
* Only apply dazed for creature attacks
* Roll dazed application on full absorbs
* Implement 0–40% dazed application chance
* ~20% at equal combat rating, ~1% change per difference of 5 (1 level).
* Fix physical spell hit chance being reduced by armor
=> Finish dazed implementation

etc/databases/world/updates/updates.sql
Closes #1141 
Relocated her approximately to position seen on the screenshot in the issue, changed level to 10 as on screenshot and tweaked the stats to match non-elite lvl 10 NPCs.
Closes #1137 
Spawned him at approximately the same position as seen on the screenshot from the issue, changed his level from 57 to 27 and changed stats to  ones seen on non-elite NPCs at lvl 27.
Closes #1138 
Spawned him at the location seen on the screenshot in the issue, changed level to 42 and his stats to those of Narkk a lvl 42 NPC standing next to him
Closes #1132 
Spawned Shaia as seen on screenshot in the issue and Lewin in a house nearby over another Leather Armor merchant. Changed both of them to level 30 same as all shop NPCs in the area. Updated their stats to suite the level.
=> Relocated and Spawned NPCs

game/world/managers/CommandManager.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/units/movement/behaviors/ChaseMovement.py, game/world/managers/objects/units/movement/helpers/SplineBuilder.py, game/world/managers/objects/units/player/quest/QuestManager.py
- Merge results from both query_heights and query_z in calculate_z in order to reduce cases in which Namigator returns above wmo Z's.
- Prevent Charge/HeroicLeap from triggering on Z locked result. (Unable to calculate a valid Z)
- Update unit Z upon forced movement manager stop() calls which interrupts an active spline.
=> Namigator tweaks.

etc/databases/world/updates/updates.sql
Razorfen Down
==========
Razormane mobs should use white quilboar, except scale there is only 2 very similar models avalaible. We will use one for caster and other for melee with 1.0 scale. We will use a 1.5 scaled models for named.
We will also apply the boar model for boars : Aga'mar Rotting Aga'mar Raging Aga'mar
Deadmines
==========
There is no parrot model for 0.5.3 (at least i cant find one). It seems that a special carrion bird placeholder was used.
Unused 0.2 scaled carrion bird, it's the same size as a parrot.
Shadowfang
========
Wolf should use black model.
We also update Vile Bat missing display_id
Wailing Cavern
=========
We will use NE PH for NE missing display_id
We will use Naga PH for Naga missing display_id
We will use right scaled turtle display_id (only one model for …
=> Instance display_id rework

etc/databases/world/updates/updates.sql
Sunken Temple
===========
Change Entrance Troll model to PH (pink one). All entries are very high (5k+), they should use the newer PH model.
Change Murk mobs to Wind serpent model.
Uldaman
=========
Update shadowforge model with dark iron models. At this point, these mobs could only use dwarf standard placeholder or dark iron models. Since they are from dark iron faction, it makes sense to use dark iron ones.
We  resolve some missing gnoll models with right scaled ones.
We fix Archadeas position and display_id (we only have one giant model)
=> Sunken Temple and Uldaman Rework

database/world/WorldDatabaseManager.py, database/world/WorldModels.py, game/world/WorldLoader.py, game/world/WorldManager.py, game/world/WorldSessionStateHandler.py, game/world/managers/maps/Cell.py, game/world/managers/maps/GridManager.py, game/world/managers/objects/farsight/Camera.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/movement/MovementInfo.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py, game/world/opcode_handling/handlers/interface/CharCreateHandler.py
- Short circuit spell/aura interrupt checks.
- Do not update creatures which are not yet ready.
- Improve creatures lazy initialization time by caching level stats.
- Decouple known object updates, one scheduler per object type.
- Creatures swing timers should be updated when out of combat.
- Moveflags reset should be notified to surroundings upon dying. (Fixes sliding corpses).
=> Update system and minor fixes.

game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/EnchantmentManager.py, game/world/managers/objects/units/player/InventoryManager.py, game/world/managers/objects/units/player/SkillManager.py
* Fix spell misses and melee spells not triggering procs (closes #1180)
* Fix periodic proc spells not ignoring cast time (Hellfire)
* Fix pets being able to target enemies with helpful spells
* Fix enchants not applying when swapping two items with the same enchant
* Fix equipment stats/enchants persisting if destroyed while equipped
* Fix weapon skills learned from trainers having a max skill of 1000
* Correct skill gain formulas for combat skills
=> Spell, equipment and skill bug fixes

etc/databases/world/updates/updates.sql, game/world/managers/objects/units/player/quest/ActiveQuest.py
Closes #1009
Closes #1162
Partial #1149 @GizzleBizzle , this are the tasks that should be checked plus what @geo-tp did on a previous commit #1195:
```
-- Ironforge Mountaineer's stats.
-- Change Frostmane Hold quest's experience reward.
-- Change A Favour for Evershine quest's experience reward.
-- Unequip Mountaineer Barleybrew
-- Change A Pilot's Revenge quest's experience reward.
-- Change an Elite's lvl.
-- Change Evershine quest's experience reward.
-- Change binders' lvls. Kerik Firebeard and Fulgar Iceforge should be changed to lvl 65.
-- Rudra Amberstill should /beg when offering the Protecting the Herd quest.
-- Change Coldridge Mountaineers' lvl and equipment.
-- Change an NPC's subname, Keeg Gibn should have a subname.
-- Change an NPC's subname.
-- Ironforge Guards should be …
```
=> Fix crash.

game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/pet/ActivePet.py, game/world/managers/objects/units/player/StatManager.py, game/world/opcode_handling/handlers/spell/CancelCastHandler.py
* Fix harmfulness for some spells with a self-cast component, AoE effect or neutral targets
* Fix non-channeled area auras with a duration never fading
* Fix B targets not being considered for area auras
* Fix spellcasts being interruptible after success
* Hide interrupt message when changing queued melee spell
* Implement armor bonuses from enchants
* Fix Healing Totem cooldown not unlocking if replaced
=> Spell harmfulness/interrupt fixes

game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/units/UnitManager.py
* Fix proc casts (Chilled etc.) not being displayed in combat log
* Fix damage shield effects (Lightning Shield etc.) ignoring miss result roll
Fixes both parts of #1221, but damage shield resists are not displayed in combat log.
=> Proc spell fixes

etc/databases/world/updates/updates.sql
all in reference to issue [#1202](https://github.com/The-Alpha-Project/alpha-core/issues/1202)
Changed Oasis Snapjaws to Mud Threshes
added this characteristics:
have the name Mud Thresh
have the DisplayID of 1752
use the same abilities as oasis snapjaws (sling dirt) be the same lvl as oasis snapjaws (the only screenshot where their lvl is seen is lvl 15 and the quest lvl didn't change between 0.7 and 1.12.1) should have "AQUATIC = 262144" flag, since all threshadons can't leave water and walk on land.
need to work out how to remove only this spawn locations: -1117.6 -2031.12 85.6693 1
-1122.4 -2086.23 80.3876 1
-1111.46 -2126.04 78.6348 1
-1130.84 -2252.62 80.4574 1
-1084.52 -2248.63 78.6269 1 
-1052.88 -2203.54 82.3212 1
-1240.82 -2950.69 92.3646 1
-1334.19 -3014.49 91.2894 1
-1316.63 …
=> Update to barrens oases chain rework #1202 updates.sql

etc/databases/world/updates/updates.sql, game/world/managers/CommandManager.py, game/world/managers/objects/ai/PetAI.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/pet/ActivePet.py, game/world/managers/objects/units/pet/PetData.py, game/world/managers/objects/units/pet/PetManager.py
* Implement basic pet autocast behavior
* No spell-specific behavior, no global cooldown etc. Simply casting harmful spells on cooldown in combat, helpful outside of combat on master
* Fix pet saving crashes related to new creature stat system
* Fix some pet trainers having an invalid trainer id
* Fix player-controlled pets dazing players
* Fix .die crashing when used on a player (warrior?) in godmode
=> Pet autocast implementation, bug/crash fixes

game/world/managers/objects/ai/PetAI.py, game/world/managers/objects/units/pet/PetData.py, game/world/managers/objects/units/pet/PetManager.py
* Fix crash when attempting to save pet data
* Correct pet spell autocast logic to only cast helpful spells when not in combat
* Handle attempting to recast pet area auras as canceling them
* Only autocast healing spells when target isn't at max health
=> Pet autocast and saving bug fixes

etc/databases/world/updates/updates.sql
Items display_id
=============
Weapons
---------
Models from vanilla are already available for some weapons, we will use it.
Shields
---------
Models from vanilla are already available for some shields and bucklers we will use it.
Ring
-----
Since ring doesn't have a visible models, we will use a PH display_id with the first ring icon (inv_jewelry_ring_01)
Cloak
------
inv_robe_02 seems to be PH for cloth cloak icons
inv_misc_pelt_wolf seems to be PH for leather cloak icons
We also apply a inv_misc_cape_02 icon for 2 mail cloak missing them.
=> Weapons, Shield and non visible items display fixes

database/world/WorldDatabaseManager.py, database/world/WorldModels.py, etc/databases/world/updates/updates.sql, game/world/WorldLoader.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/StatManager.py, utils/constants/SpellCodes.py
* Fix aura remove being called multiple times sometimes (closes #1258)
* Implement scripted spell targets (#1258, fixes Gnarlpine Vengeance having incorrect targets)
* Fix Battle Stance application showing an error to warriors when respawning
* Refactor spell initialization flow to be more consistent with how parameters are passed
=> Implement scripted spell targets, refactoring

game/world/managers/objects/ai/AIFactory.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/movement/MovementManager.py, game/world/managers/objects/units/pet/PetManager.py
* Fix charm auras not working due to evade clearing auras
* Fix enemies attacking pet's owner if pet initiates combat by missing
* Make temporarily charmed creatures use same AI and movement as permanent pets
* Fix AoE spell effects failing to resolve targets
* Fix some AoE effects incorrectly excluding the caster
* Fix stacking auras not stacking
* Initialize creature stats before applying default auras
* Stats being updated (due to aura application) when uninitialized leads to a crash after previous StatManager update
* Fix DoT auras from on-swing spells and dodged/blocked/parried spells proccing dazed
* Fix auras from dead enemies not being dispellable
=> Various pet/spell bug fixes

etc/databases/world/updates/updates.sql
Closes #1293 
- Resets all binding on armor and weapons.
- Makes all rings Unique.
- Sets all instanced boss drops, instanced rare spawn drops and rare crafted items to Bind on Equip.
- Sets all dungeon quest rewards to Bind on Pickup.
Note: instanced rare spawns aren't bosses, but I've added them anyway unless @GizzleBizzle tells me not to.
=> Binding system rework

game/world/managers/objects/units/player/InventoryManager.py, game/world/opcode_handling/handlers/inventory/SplitItemHandler.py, game/world/opcode_handling/handlers/inventory/SwapItemHandler.py
- Closes #1367
- Fix not being able to Split->Stack items from/to bank bags slots.
- Fix frozen inventory updates after swapping/splitting items from a bank bag into player bags.
=> Inventory fixes.

database/realm/RealmDatabaseManager.py, etc/databases/world/updates/updates.sql, game/world/managers/objects/units/player/InventoryManager.py, game/world/opcode_handling/handlers/npc/SellItemHandler.py
- Fix invisible items in the backpack upon using .additem, reported by Davir.
- Fix Inventory update bug when dealing with 20 slot bag.
- Fix crash when selling the item at slot 19 from a 20 slot bag.
/ 20 slot bags are not normally available, other bugs/crashes might occur since container slot 19 can be mistaken with BAG_SLOT 19.
=> Inventory.

game/world/managers/objects/units/player/StatManager.py
* Replace placeholder crushing blow chance calculation with vanilla formula (15% + 2% * rating difference)
* Minor refactoring to `get_attack_result_against_self`
=> Add crushing blows formula

etc/databases/world/updates/updates.sql
Automated using a script to compare data between 1.2 and 0.5.3
1. Retrieve all items where `display_id > 11802` and `entry < 6439`.
2. Iterate over each of them and retrieve the `vmangos.ItemDisplayInfo` related to the `display_id` for each entry.
3. Compare `vmangos.ItemDisplayInfo` with `alpha_dbc.ItemDisplayInfo` to find a model in the 0.5.3 range with the exact same model fields.
**Note**: The icon should not be `NULL`, or the model will not be updated. This happens when the exact model is found but no icon is associated with the `display_id`.
Since we know that most of the items were updated because of the icon, it makes sense to use this approach to resolve the remaining `display_id` entries.
```
['ModelName1', 'ModelName2', 'ModelTexture1', 'ModelTexture2', 'Texture1', 'Texture2', …
```
=> Update missing items display_id

game/world/WorldManager.py, game/world/managers/maps/Cell.py, game/world/managers/maps/GridManager.py, game/world/managers/maps/Map.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/gameobjects/managers/TransportManager.py, game/world/managers/objects/units/movement/MovementInfo.py, game/world/opcode_handling/handlers/player/MovementHandler.py
* Fix transport update and path node loading
* Send transport location in place of world location in movement updates when within transports
* Closes #978
* When entering transports, don't broadcast movement updates until transport GO has updated
* This consistently prevents players from disappearing for each other when entering transports, but results may vary when latency is involved
* Players can still disappear for each other when quickly leaving and entering a transport, or rarely when jumping into the transport. 
* Consistency could possibly be improved by forcing the transport to update soon after passengers are added
* Update transports every 100ms to reduce skipped movement packets
=> Improve movement updates within transports

etc/databases/world/updates/updates.sql, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/creature/utils/TrainerUtils.py, game/world/managers/objects/units/pet/PetData.py, game/world/managers/objects/units/pet/PetManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/SkillManager.py
* Fix pet passive effects not being applied
* Fix max level hunters' pets not gaining experience
* Don't automatically learn hunter pet talents on tame
* Fixes hunter pets learning all possible passive talents
* These spells lack level data, and training level requirements would be tricky to load
* Fix race/class restriction check for talents
* Fixes Bow Specialization not being available for hunters using bows
* Don't interrupt physical spells from crushing blows
* 0.5.3: `Creatures dealing enough damage (crushing blow) will now fully interrupt casting`
* Patch notes probably don't refer to abilities with "casting"
* Fix lower rank abilities persisting in spellbook (after relog) when a new rank is learned
* Fix `Minor Healthstone` spell data and rename to `Minor Bloodstone`
* Closes …
=> Bug fixes!
