game/world/managers/objects/player/InventoryManager.py, game/world/opcode_handling/handlers/BuyItemInSlotHandler.py
Added bag checks to is_inventory_pos, fixed buying bags straight to bag slots and fixed some bugs in swap_item.
=> Fix some inventory bugs

database/realm/RealmDatabaseManager.py, game/world/managers/objects/player/InventoryManager.py
Implement saving container contents to database and getting an ordered container dict.
=> Inventory fixes

database/world/WorldDatabaseManager.py, game/world/WorldLoader.py, game/world/managers/objects/CreatureManager.py, game/world/managers/objects/item/ItemManager.py, game/world/managers/objects/loot/LootManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/loot/LootItemHandler.py, game/world/opcode_handling/handlers/loot/LootMoneyHandler.py, game/world/opcode_handling/handlers/loot/LootReleaseHandler.py, game/world/opcode_handling/handlers/loot/LootRequestHandler.py, utils/constants/UpdateFields.py
/ Quest items are not filtered yet.
=> Basic creature loot implementation.

game/world/managers/objects/LootManager.py, game/world/managers/objects/creature/CreatureManager.py, game/world/managers/objects/player/InventoryManager.py, game/world/managers/objects/player/PlayerManager.py
/ Client should no longer close loot window when dealing with more than 2 items.
/ Check for inventory space before looting an item.
=> * Fix two loot bugs.

game/world/managers/GridManager.py, game/world/managers/objects/creature/CreatureManager.py, game/world/managers/objects/player/GroupManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/group/GroupUnInviteGuidHandler.py
+ Implement CMSG_GROUP_UNINVITE_GUID
*  Update all party member stats when a new member joins
*  Merge kick_member() into leave_party()
=> + CMSG_GROUP_UNINVITE_GUID & fixes.

game/world/managers/objects/UnitManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/player/SpellManager.py
Implements melee spells, combo points and resource costs for spells. Also includes some general refactoring of SpellManager and at least technically allows the usage of UnitManager with a SpellManager.
=> SpellManager fixes and features, combo point implementation

game/world/managers/objects/ChannelManager.py, game/world/managers/objects/player/FriendsManager.py, game/world/opcode_handling/handlers/group/GroupInviteHandler.py
Fix FriendsManager persistence bug related to ignores.
Fix FriendsManager sending offline/online notifications to ignored players.
Fix ignored players being able to request a group invite.
=> Check social ignore when sending channel messages.

game/world/managers/CommandManager.py, game/world/managers/objects/UnitManager.py, game/world/managers/objects/player/InventoryManager.py, game/world/managers/objects/player/SkillManager.py, game/world/managers/objects/player/SpellManager.py
This PR fixes errors relating to casting ranged attacks and implements reagent costs. Also includes changes to InventoryManager related to reagent handling and a minor fix to equipment checking so that guns can be equipped.
=> Minor fixes to spell handling and inventory

database/dbc/DbcDatabaseManager.py, game/world/managers/CommandManager.py, game/world/managers/objects/GameObjectManager.py, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/UnitManager.py, game/world/managers/objects/creature/CreatureManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/SpellManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/spell/CancelAuraHandler.py
This PR implements native values for display_id and scale for objects, proper aura cancellation logic and aura cancel packet handling. Also includes a fix for a client crash in SpellManager and some cleanup.
=> Implement native display id and scale + more aura features

game/world/WorldManager.py
/ Do not use a fixed buffer, use the actual header size field to request the proper payload to read and make sure we do read all remaining bytes from the socket.
/ Modified incoming queue to handle PacketReader objects instead of raw buffers.
=> Rcv socket improvements.

game/world/managers/objects/creature/CreatureManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/SpellManager.py
This PR implements proper index handling for auras and aura updates on creatures. Also restructures AuraManager and fixes mount behavior.
=> Aura indexing and fixes to effect handling

game/world/WorldManager.py, game/world/WorldSessionStateHandler.py, game/world/managers/objects/UnitManager.py, game/world/managers/objects/player/PlayerManager.py, utils/Formulas.py
=> GIVE ME RAGE!

game/world/managers/objects/player/PlayerManager.py
/ Money 'sound' should no longer trigger twice making you feel rich.
=> * Fix money loot bug.

game/world/managers/objects/player/QuestManager.py, utils/constants/ObjectCodes.py
- rename QuestStatus to QuestState. match the client
- lookup quest state when sending quests to questgiver
- mark delay and emoteID in SMSG_QUESTGIVER_QUEST_LIST
- make initial quest class
=> quest changes

game/world/managers/objects/player/QuestManager.py
- rename self.quests to self.active_quests, to clearly distinguish active quests from templates
- add a note about terminology
- update quest giver status code to prioritize quest turnin status
- if a quest giver can't be the quest turnin, then don't put the quest in their list
- add finish quests to turn-in npc's quest list
- add generate_req_source_list, generate_req_source_count_list and generate_req_spell_cast_list
- fixup add_quest and send_quest_query_response to support active quest class
- new code to track quest completion
- is_instant_complete_quest
- can_complete_quest
- complete_quest
=> quest improvements

game/world/opcode_handling/handlers/unit/SetSelectionHandler.py, game/world/opcode_handling/handlers/unit/SetTargetHandler.py
* Circumvent set_target through set_selection. Check comments.
=> * Fix loot kneeling not showing up to other players.

game/world/managers/objects/player/QuestManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/quest/QuestGiverRemoveQuestHandler.py
- support quest remove
- fix a bug where quests in the player's questlog were affecting the quest giver's status (hat tip to Titi)
=> quest remove. giver status bugfix

game/world/managers/objects/LootManager.py, game/world/managers/objects/creature/CreatureLootManager.py, game/world/managers/objects/creature/CreatureManager.py, game/world/managers/objects/player/PlayerManager.py
/ Only drop quest items if the killer or his group needs them.
/ Only those players that require it will be able to see it in their loot window.
=> Loot - quest items

game/realm/RealmManager.py, game/world/WorldManager.py
/ Also use the right config field ip:port for each socket.
=> * Display real socket bindings upon start.

database/realm/RealmDatabaseManager.py, database/realm/RealmModels.py, etc/databases/realm/updates/updates.sql, game/world/WorldLoader.py, game/world/managers/objects/player/GroupManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/player/guild/GuildManager.py, game/world/opcode_handling/handlers/group/GroupDisbandHandler.py, game/world/opcode_handling/handlers/group/GroupInviteDeclineHandler.py, game/world/opcode_handling/handlers/group/GroupInviteHandler.py, game/world/opcode_handling/handlers/group/GroupLootMethodHandler.py, game/world/opcode_handling/handlers/group/GroupSetLeaderHandler.py, game/world/opcode_handling/handlers/group/GroupUnInviteGuidHandler.py, game/world/opcode_handling/handlers/group/GroupUnInviteHandler.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py
/ Added missing packet SMSG_GROUP_DESTROYED when the party is disbanded.
/ Modified most of the group manager code in order to drop strong references, we now use mostly guids.
=> Groups persistence.

game/world/managers/objects/creature/CreatureLootManager.py, game/world/managers/objects/player/GroupManager.py, game/world/opcode_handling/handlers/group/GroupInviteHandler.py, game/world/opcode_handling/handlers/group/GroupSetLeaderHandler.py, game/world/opcode_handling/handlers/group/GroupUnInviteGuidHandler.py, game/world/opcode_handling/handlers/group/GroupUnInviteHandler.py
* Fix some conditions that were causing a crash on group handlers.
=> * Fix group allowed looters.

game/world/managers/objects/player/GroupManager.py, game/world/opcode_handling/handlers/player/RandomRollHandler.py
* Fix crashes related to GroupDeclineInvite handler.
* Group - Modify the way we build SMSG_GROUP_LIST.
=> More group fixes.

game/world/managers/maps/GridManager.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/player/PlayerManager.py, utils/constants/ObjectCodes.py
/ Base relocate upon active cells and destination vector.
=> * Near teleport will no longer trigger a Create update packet.

game/world/managers/maps/GridManager.py, game/world/managers/maps/MapManager.py
/ Load tiles for all creatures in the cell becoming active.
=> * Fix on_cell_turn_active callback.

game/world/managers/objects/player/GroupManager.py, game/world/managers/objects/player/InventoryManager.py, game/world/opcode_handling/handlers/world/ZoneUpdateHandler.py
* Notify group members loot to surrounding party members.
* Fixes to how we build and send party members stats.
/ Offline members should now at least display with no health and no power.
=> * Group fixes/changes.

database/dbc/DbcDatabaseManager.py, game/world/managers/maps/GridManager.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/UnitManager.py, game/world/managers/objects/creature/CreatureManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, utils/constants/SpellCodes.py
This PR includes changes to spell targeting and aura handling for AoE and periodic spell implementation. 
Channeled spells also somewhat work now, but the client-side animations seems to be broken. spell_go is sent on channel ticks as a hackfix for now.
=> Implementation for AoE, periodic and channeled spells

database/dbc/DbcDatabaseManager.py, database/world/WorldDatabaseManager.py, game/world/WorldLoader.py, game/world/managers/maps/MapManager.py, game/world/managers/maps/MapTile.py, game/world/managers/objects/player/GroupManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/opcode_handling/handlers/social/WhoHandler.py, game/world/opcode_handling/handlers/world/ZoneUpdateHandler.py
/ Fix bug in which party members location would not display on the other party clients unless they were in range.
/ Fixed get_area_flags returning area_terrain information.
=> * Party members location should now display properly if out of range.

game/world/managers/maps/MapManager.py, game/world/managers/objects/player/FriendsManager.py
/ Friend list only likes root zone id's.
=> / Fix friend list displaying 'Unknown' locations.

game/world/opcode_handling/handlers/player/DebugAIStateHandler.py, game/world/opcode_handling/handlers/player/DuelAcceptHandler.py, game/world/opcode_handling/handlers/player/DuelCanceledHandler.py, game/world/opcode_handling/handlers/player/InspectHandler.py, game/world/opcode_handling/handlers/player/LogoutCancelHandler.py, game/world/opcode_handling/handlers/player/LogoutRequestHandler.py, game/world/opcode_handling/handlers/player/MountSpecialAnimHandler.py, game/world/opcode_handling/handlers/player/MovementHandler.py, game/world/opcode_handling/handlers/player/NameQueryHandler.py, game/world/opcode_handling/handlers/player/PingHandler.py, game/world/opcode_handling/handlers/player/PlayedTimeHandler.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py, game/world/opcode_handling/handlers/player/PlayerLogoutHandler.py, game/world/opcode_handling/handlers/player/RandomRollHandler.py, game/world/opcode_handling/handlers/player/RepopRequestHandler.py, game/world/opcode_handling/handlers/player/SetWeaponModeHandler.py, game/world/opcode_handling/handlers/player/StandStateChangeHandler.py, game/world/opcode_handling/handlers/player/cheats/CheatSetMoneyHandler.py, game/world/opcode_handling/handlers/player/cheats/GodModeHandler.py, game/world/opcode_handling/handlers/player/cheats/LevelCheatHandler.py, game/world/opcode_handling/handlers/player/cheats/LevelUpCheatHandler.py, game/world/opcode_handling/handlers/player/cheats/SpeedCheatHandler.py, game/world/opcode_handling/handlers/player/cheats/TriggerCinematicCheatHandler.py
Implemented type hinting where it serves a purpose in player opcode handlers.
=> Implement type hinting in OpCode handlers

game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellManager.py, utils/constants/SpellCodes.py
This PR corrects aura slot handling (debuffs now display properly) and fixes some bugs in effect targeting. Also adds type hinting to methods where it's relevant.
=> Fixes for aura handling and effect targeting

game/world/managers/objects/player/TaxiManager.py
/ Display only those nodes discovered by the player.
=> * Persist discovered taxi nodes.

game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py
This PR fixes vector target handling, making spells like Word of Recall work properly.
=> Targeting methods clarification, teleport spells fix

game/world/WorldSessionStateHandler.py
get() method returns none if the key doesn't exist in the dictionary.
=> better performance on searching by removing useless ifs

game/world/managers/objects/item/ItemManager.py
/ This fixes CMSG_ITEM_USE not triggering on the client when items did not reside on backpack.
=> Fix ITEM_FIELD_CONTAINED.

game/world/managers/objects/player/GroupManager.py, game/world/managers/objects/player/quest/QuestManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/quest/QuestConfirmAcceptHandler.py, game/world/opcode_handling/handlers/quest/QuestGiverAcceptQuestHandler.py
* Implement CMSG_QUEST_CONFIRM, left it commented for later use once QuestSystem is more advanced.
https://i.ibb.co/LQpgS4N/Share-Quest.jpg
* Validate MAX_QUEST_LOG upon accepting a quest.
* Groups - Destroy persisted group upon loading if real member length is less than 2.
=> CMSG_QUEST_CONFIRM and other minor fixes.

game/world/managers/objects/UnitManager.py, game/world/managers/objects/spell/AppliedAura.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/CooldownEntry.py, game/world/managers/objects/spell/SpellManager.py, game/world/opcode_handling/handlers/spell/UseItemHandler.py, utils/constants/SpellCodes.py
- Implement casting spells with items and item charge handling.
- Add handling for AuraInterruptFlags
- Implement better cooldown handling with category checks (in SpellManager for now, no persistence).
- Fix combat bug with self-damaging spells
=> Item spells, AuraInterruptFlags and better cooldown handling

game/world/managers/objects/UnitManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/SpellEffectHandler.py
Basic implementation of healing spells, both periodic and regular heals.
=> Healing spell (aura, cast) implementation

game/world/managers/objects/UnitManager.py, game/world/managers/objects/creature/CreatureManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/spell/AppliedAura.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/spell/CancelAuraHandler.py, game/world/opcode_handling/handlers/spell/CancelCastHandler.py, game/world/opcode_handling/handlers/spell/CancelChannellingHandler.py, game/world/opcode_handling/handlers/spell/CastSpellHandler.py, utils/constants/SpellCodes.py
- Implement spell pushback - required major refactoring to periodic effect handling.
- Implement spell interrupt checks
- Fixes to SpellManager delay handling + multitarget delay implementation
- Implement better combat logging for spellcasts + working damage number visuals
- Implement minor spell-related packet handlers
- Fix various minor issues related to arcane missiles implementation
=> Major refactoring to periodic effect handling, spell interrupts+pushback and proper damage handling

etc/config/config.yml.dist, game/world/managers/maps/AreaInformation.py, game/world/managers/maps/Constants.py, game/world/managers/maps/MapManager.py, game/world/managers/maps/MapTile.py, game/world/managers/objects/player/PlayerManager.py, game/world/opcode_handling/handlers/player/MovementHandler.py, game/world/opcode_handling/handlers/world/ZoneUpdateHandler.py, main.py, utils/ConfigManager.py
MapManager:  Capability to retrieve AreaNumber, AreaFlags, AreaExploreBit, AreaLevel and AreaFactionMask.
Fix multiple exploration problems, including zone_check not triggering at all due CMSG_ZONEUPDATE not triggering client side.
Use version in configuration file.
=> Exploration and new map file version 1.10.

game/world/opcode_handling/handlers/npc/ListInventoryHandler.py, game/world/opcode_handling/handlers/npc/TrainerListHandler.py
- Replaced calls to QuestGiverHelloHandler.handle() with handle_quest_giver_hello() in QuestManager so one opcode handler isn't calling another
=> Refactors to trainer/vendor list opcode handlers

game/world/managers/maps/AreaInformation.py, game/world/managers/maps/Map.py, game/world/managers/maps/MapManager.py, game/world/managers/maps/MapTile.py, game/world/managers/objects/player/PlayerManager.py
/ Keep track of which tiles have been loaded already.
/ If an entity request map files Z of a non active cell (like a wandering mob), try to load that tile as well if there were no previous attempts.
/ Orcs, Taurens and Night Elfs should no longer receive exploration experience upon entering world in their start locations.
=> New map files version 1.20 and exploration bug fixes.

etc/databases/world/updates/updates.sql
/ Remove invalid spawns on old Darnassus FM location.
=> Relocate Ironforge and Darnassus FlightMasters based on dbc taxi info.

game/world/managers/objects/UnitManager.py, game/world/managers/objects/player/DuelManager.py, game/world/managers/objects/spell/AppliedAura.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, utils/constants/SpellCodes.py
- Fix impact delay handling. (fixes more complex spells like Explosive Shot)
- Fix bugs with aura duration and teleport spell target selection.
- Refactor energize effect handling and implement periodic energize aura effect (drinking).
- Implement basic aura proc handling and add effect_target to AuraEffectHandler.
=> Bug fixes and basic aura proc implementation

game/world/managers/objects/spell/EffectTargets.py
Fixes arcane missiles targeting.
=> Ignore empty implicit target in target_b.

game/world/managers/objects/player/PlayerManager.py
/ Map 0 should not resolve as false.
=> Fix teleport bug.

game/world/managers/objects/creature/CreatureManager.py, game/world/opcode_handling/handlers/npc/TrainerBuySpellHandler.py, game/world/opcode_handling/handlers/npc/TrainerListHandler.py
/ Allow TradeSkills, Mounts and Pet trainers requests to go through the handler.
=> Some trainer handler refactoring.

game/world/opcode_handling/handlers/group/GroupInviteHandler.py
Fixed a bug that allows a player to invite & join a group with themselves, causing character-breaking issues.
=> Group invite self bug fix

game/world/managers/objects/ObjectManager.py, game/world/managers/objects/UnitManager.py, game/world/managers/objects/creature/CreatureManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/player/StatManager.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/SpellEffectHandler.py
- Modify StatManager to allow usage with UnitManager (stat mod AuraEffects now work on creatures).
- Refactoring for school vulnerability implementation.
=> StatManager for units and school vulnerability

game/world/opcode_handling/handlers/player/LogoutRequestHandler.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py
/ Do not sit upon LogoutRequest if swimming.
/ Do not set PlayerMgr session twice.
=> Minor fixes.

game/world/managers/maps/MapManager.py, game/world/managers/maps/MapTile.py
/ Parse only valid area and liquid information.
/ This should also minimize wrong water detection when walking over solid terrain on places like Wetlands and Unguro.
=> Stage new map files version 1.40.

etc/databases/world/updates/updates.sql, game/world/managers/objects/creature/CreatureManager.py
- Simplified send_trainer_list code
- Fixed Ice Armor (Rank 2) training
- Fixed Nullify Disease (Rank 2) training
=> Training Refactors & Spell Fixes

database/world/WorldDatabaseManager.py, database/world/WorldModels.py, game/world/WorldLoader.py, game/world/managers/objects/player/quest/QuestManager.py
- Implementation of basic questgiver/npc gossip messages using preexisting tables: npc_gossip, npc_text. No database updates
- Most npcs should now have fitting gossip messages which can be worked on and changed to fit 0.5.3 in the future
=> Basic Questgiver Gossip

game/world/managers/CommandManager.py
- `.additem` now supports second argument for quantity, eg `.additem 1234 10` to add a stack of 10 of item 1234.
- New command: `.additems`, will add multiple items in the backpack. eg `.additems 123 234 345 456 654`.
- New command: `.addskills`, will add multiple skills to the character. eg `.addskills 14 15 16`.
- New command: `.addspells`, will add multiple spells to the character. eg `.addspells 567 678 789`.
=> Enhance GM commands

game/world/managers/maps/MapManager.py, game/world/managers/maps/MapTile.py, game/world/managers/objects/player/PlayerManager.py
/ Set tile information back to None if unable to load a map file.
/ Validate teleport destinations towards map tiles.
=> Teleport and Tile fix.

game/world/managers/objects/spell/SpellEffectHandler.py
Use regular skill ID when loading languages.
=> Fix applying language passive

game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/player/PlayerManager.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/opcode_handling/handlers/npc/TrainerBuySpellHandler.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py
- Implement handle_summon_object, summoned object positioning cases and other logic required for Ritual of Summoning.
- Refactor target handling for resolve_minion.
- Modify start_spell_cast arguments to better match existing usage.
=> Ritual of Summoning implementation, refactoring

game/world/managers/objects/UnitManager.py, game/world/managers/objects/player/StatManager.py
- Fix base speed being set to unit total speed on level up.
- Fix unit base speed being set to 0 when calling change_speed(0).
=> Unit speed bug fixes.

etc/databases/world/updates/updates.sql
- Bank GameObjects
-  NPC display_id resolved
- Gryphons
- Canal GameObjects
=> Stormwind Improvements

game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py
- Players participating in the ritual now channel the ritual spell.
- The actual summon spell is now a hidden trigger.
- Ritual participation is limited to the caster's group.
=> Improved Ritual of Summoning behavior

database/world/WorldDatabaseManager.py, etc/databases/world/updates/updates.sql, game/world/opcode_handling/handlers/interface/CharCreateHandler.py
- Add class and race buttons when character is created
- Fix database playercreateinfo_action to fit 0.5.3
=> Add default buttons for created characters

etc/databases/world/updates/updates.sql
- Resolved display id
- Add trainers
- Despawned NPC not in 0.5.3
=> Stormwind More improvements

game/world/managers/objects/player/TaxiManager.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py
/ Remove PlyrMgr load_self, create packet is sent upon complete_login.
=> Fix taxi resume bug when restarting the server.

game/world/managers/abstractions/Vector.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/units/MovementManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/taxi/TaxiManager.py, game/world/managers/objects/units/player/taxi/TaxiResumeInformation.py, game/world/opcode_handling/handlers/player/MovementHandler.py
/ Flight resume should be working again.
/ Modified some cases to not delay teleport action. (Sitting on a chair, 'landing' from a taxi, etc)
/ Upon teleporting on the same map/cell player should notify surroundings with a partial update packet.
=> More taxi/teleport fixes.

game/world/managers/objects/units/creature/CreatureManager.py
/ Fix bug in which melee target would never attack the player due distance check.
=> Fix melee combat bug.

game/world/managers/objects/spell/AppliedAura.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/managers/objects/units/player/StatManager.py, game/world/opcode_handling/handlers/inventory/SplitItemHandler.py, game/world/opcode_handling/handlers/spell/CastSpellHandler.py, game/world/opcode_handling/handlers/spell/UseItemHandler.py
- Implement aura rank exclusivity.
- Aura bounce (stronger effect applied) implementation.
- Implement defensive stat bonus auras.
- Implement proper item spell cast targeting.
- Add clarifying comments for aura handling.
Minor bug fixes:
- SkillManager can_ever_use_equipment fix.
- Use correct target in leech aura effect.
- Use correct proc flags in check_aura_procs for dodge/parry/block.
- Fix removing auras on 0 proc charges.
- Fix channeled, next swing spell handling (Garrote).
- Fix strength block scaling.
- Fix issue with splitting item stacks.
=> Minor spell/aura fixes and features.

game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/managers/objects/units/player/StatManager.py
* Make power type changeable to modify it based on shapeshift form.
* Ignore melee weapons and skill for feral druids.
* Fix attack damage for feral druids, based on vanilla values.
=> Feral druid attack behavior fixes

docker-compose.yml
So I can create other docker containers on the same network as Alpha-core
=> added a network name docker-compose

game/world/managers/objects/spell/AppliedAura.py, game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, utils/constants/SpellCodes.py
* Correct charge target resolving to match usage in Spell.dbc.
* Modify effect handling to match targeting.
* Move get_position_for_charge.
* Add validation for secondary unit targets on cast.
* Enable minimum range checks for spells.
* Fix cast interrupting and aura removal on unit death.
* Fix effect loading for spells with invalid effects.
=> Charge spell refactoring and target validation, fix for effect loading.

game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellManager.py
* Fix bug preventing wand shooting.
* Properly consume thrown weapons.
* Fix spell_go packets for gameobjects.
=> Ranged weapon and gameobject cast packet bug fixes

game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/StatManager.py
Add critical chance on melee attack based on player strength/critical and defense/weapon skill
=> Critical strike for melee attack

game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py
* Fix Resurrection Sickness stat modifier application.
* Floor base attack and spell damage after bonus application.
* Fix updating max health and mana.
* Fix power cost handling when a spell modifies the player's power type (fixes #243).
* Handle edge cases for spell effect and aura mounting interaction.
=> Minor Aura/Stat/Spell bug fixes

game/world/managers/objects/units/player/InventoryManager.py, game/world/managers/objects/units/player/quest/ActiveQuest.py, game/world/managers/objects/units/player/quest/QuestManager.py
/ When removing items, updated any related quest required items by using the player inventory.
=> Fixed corrupted quest states after destroying items.

game/world/managers/objects/spell/AuraManager.py
* Fix auras with `negative_spell` interrupt flag instantly cancelling on application.
* Refresh existing auras on reapplication instead of removing and applying.
=> Aura application fixes

game/world/managers/objects/spell/SpellEffectHandler.py
The effect currently used in 'Lay on Hands' Paladin spell. Its description states:
> Heals a friendly target for an amount equal to the Paladin\'s maximum health...
=> Implement max health heal effect

game/world/managers/objects/item/ContainerManager.py, game/world/managers/objects/units/player/InventoryManager.py
/ Do not consider container as full if we are swapping (not adding) an item.
=> Fix issue #268

game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/quest/ActiveQuest.py, game/world/managers/objects/units/player/quest/QuestManager.py
/ Fixed quest check requirements for negative PrevQuestID.
/ Added TODO note regarding interactive gos.
=> Quest crash fix & Fix rage decay.

database/realm/RealmDatabaseManager.py, game/world/managers/CommandManager.py, game/world/managers/objects/spell/SpellManager.py
- Unlearn spell by id
- Unlearn talent using it spell id and return talent cost to player
=> Unlearn spell command

database/dbc/DbcDatabaseManager.py, game/world/WorldManager.py, game/world/WorldSessionStateHandler.py, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/CooldownEntry.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/interface/AuthSessionHandler.py, game/world/opcode_handling/handlers/spell/CastSpellHandler.py
- A little bit of typing for spell logic understanding, cleaning code
- Add threat to all creatures which the healing target is attacking now
=> Healing threat generation

game/world/managers/objects/spell/AuraManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py
* Fixes auras not displaying for the player after changing map.
* Refactor aura update logic to be more versatile.
=> Refactor aura update handling, fix visual bug when relocating

game/world/managers/objects/ObjectManager.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/player/PlayerManager.py, network/packet/update/UpdatePacketFactory.py
/ Remove 'override' behavior.
/ Player log should no longer display auras casted again upon teleport (Animation does show up)
/ Fix bonuses not refreshing after teleport.
/ Fix SpellManager crash.
=> Minor changes to Update System, fixed SpellMgr crash.

game/world/managers/CommandManager.py
hi, this PR add a message to tel what command do
=> Improve help message

etc/databases/world/updates/updates.sql
should fix this issue
https://github.com/The-Alpha-Project/alpha-core/issues/295
=> fix disaply_id, add equipement_id, position

etc/databases/world/updates/updates.sql, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/quest/QuestManager.py
/ Flush attackers collection upon dying.
=> / Fix quest item rewards quantity.

etc/databases/world/updates/updates.sql
Resolved Issue #300 
- Fix Elaine Trias display id and location
- Fix Corbett Schneider display id
=> Edit Elaine Trias/Corbett Schneider

game/world/managers/objects/timers/MirrorTimer.py, game/world/managers/objects/units/MovementManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/player/PlayerManager.py
/ MovementManager - Fix send_stop() issues, causing corpses to keep moving upon dying.
/ ThreatManager - Reset upon owner leave_combat()
/ ThreatManager - pop dead or evading units automatically upon target acquisition.
/ MirrorTimerDamage log handling. (Drowning and Exhaustiion)
/ Changes to SMSG_DAMAGE_DONE, allow dots and cast on swing spells to display damage (e.g. Rend, Strike) without sending an attack update packet which was interrupting cast animation on spells like Strike.
=> / Fixes (MovementManager & ThreatManager) 

game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/player/EnchantmentManager.py
* Fix self-target check in add_threat. 
* Closes #340. Thrash's negative aura application was adding threat for the caster against self.
* Ignore power type and cast time for proc spells.
=> Minor spell bug fixes

etc/databases/world/updates/updates.sql, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, utils/Formulas.py
* Remove charges from bandages - first aid spells have reagent costs in 0.5.3. Closes #351.
* Implement Overpower proc case. Closes #352.
* Add required Gameobject focus checks for casts. Closes #343.
* Correct ammo-related cast results.
=> Spell-related bug fixes

etc/databases/world/updates/updates.sql
=> Darnassus binder fix

game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/units/PetManager.py
* Only scale damage by combo points for rogues
* Add active pet check to pet action handling
=> Overpower scaling + PetManager crash fix

game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py
* Add armor mitigation based on information from archived Thottbot. Closes #373.
* Fix applying damage modifiers when the attacker is a creature
=> Armor mitigation, creature attack damage modifiers

game/world/WorldManager.py, game/world/managers/objects/ai/BasicCreatureAI.py, game/world/managers/objects/gameobjects/GameObjectLootManager.py, game/world/managers/objects/item/ItemLootManager.py, game/world/managers/objects/loot/LootHolder.py, game/world/managers/objects/loot/LootManager.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureLootManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/CreaturePickPocketLootManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/player/GroupManager.py, game/world/managers/objects/units/player/PlayerManager.py
/ ThreatManager - Basic handling for assist calls done by creatures.
/ Loot - Handle multi drop flag.
/ Loot - Fix money loot not disappearing from the loot windows for other players while in a party.
=> / Fix #376 & #372

game/world/managers/objects/units/PetManager.py, game/world/managers/objects/units/creature/CreatureManager.py
* Fix temporary pets losing their charm aura upon taming
* Validate client-provided guid in `PetManager.handle_action`
=> Charmed pet aura desync fix

game/world/managers/objects/spell/SpellManager.py
=> Fix passive effect application

game/world/managers/objects/item/ItemManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/InventoryManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/handlers/inventory/ItemQueryMultipleHandler.py
* Fixes client crash when the player has a large amount of items in their inventory
=> Limit multiple item query packet size

etc/databases/world/updates/updates.sql
De-spawns Warlock quests, warrior quests, and paladin quests added in 0.5.5
https://wowpedia.fandom.com/wiki/Patch_0.5.5
#398
#405
=> Despawn class quests added in 0.5.5

etc/databases/world/updates/updates.sql
See https://github.com/The-Alpha-Project/alpha-core/pull/387
=> Thousand needles improvements

etc/databases/world/updates/updates.sql
All game object templates with type 3 (Chest) Data0 259 should be moved to 57
Lock.dbc in alpha does not have Lock 259
So client does not know how to handle them
Thanks Devwar
=> Fix Issue #390

etc/databases/world/updates/updates.sql
=> Despawn warlock class quest game objects

game/world/managers/objects/spell/SpellManager.py
* Fix crash for other charm spells
=> Only check tame result for taming spells

etc/databases/world/updates/updates.sql
Despawn Summoning circles at brill graveyard
Remove door interaction object at brillgraveyard
Despawn quest Marla's Grave and associated objects/items
#392
=> Tirisfal glades fixes

database/world/WorldDatabaseManager.py, game/world/managers/CommandManager.py
Added Command to search quests
`.qsearch - search quests`
Usage: 
.qsearch quest name
Seen in discord it was desired by some, myself included :)
=> Added command to search quests

game/world/managers/objects/spell/SpellEffectHandler.py
* Fix crash for some vector target spells
=> Add target type check to effect immunity check

etc/databases/world/updates/updates.sql, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/units/creature/ThreatManager.py
/ Fix ThreatManager target resolver considering not spawned units.
/ ObjectManager despawn() should always set is_spawned flag to False.
=> Fix combat bug.

etc/databases/world/updates/updates.sql
Hi, this should fix #429 #442 #483 
Note that for the #483 the position of the Commander Felstrom seems strange to me
=> fix some issue on duskwood

game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/PetManager.py, game/world/managers/objects/units/UnitManager.py
* Implement ammo damage bonus
* Handle ammo level restriction
* Use correct (vanilla) values for pet damage
* Account for attack speed buffs for all units
* Fix visual bug with base armor buffs (Toughness talent)
=> Minor spell/aura/pet fixes

game/world/managers/objects/spell/SpellEffectHandler.py
=> Fix crash on weapon damage effects

game/world/managers/objects/spell/AuraEffectHandler.py, game/world/managers/objects/units/player/GroupManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/handlers/player/MovementHandler.py
Closes #358
/ Party members should now properly see other members portraits stats changes and correct location on map. (Thx @ratkosrb)
=> / Group fixes.

game/world/managers/objects/ai/PetAI.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py
/ Basic handling for SPELL_EFFECT_THREAT
/ Basic handling for SPELL_AURA_MOD_TAUNT
=> ThreatManager.

game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py
Spell Critical
=======
FIX #239 
About
-------
- Simple implementation for critical on spell. 
- Implemented in UnitManager to be avalaible for all units.
- Based on 5% default crit chance for magical spell.
- For all magical/physical spells, except healing
=> Critical for spell

etc/databases/world/updates/updates.sql
Swamp
====
Adolescent Whelp
----
Magtoor
-----
Wyrm
----
Lost One
----
There are only 2 display_id avalaible for these mobs. Some mobs already have their display_id, we apply same for mobs whose missing it.
Stonard
----
(NO MODIFICATIONS DONE)
There are 3 models of orc placeholder
The first is used mostly for mobs and npc with a realy low entry.
The second is used mostly for NPC with an high entry.
The third is used mostly for Grunt and Named.
- Model 1
863 Sonard Hunter
868 Stonard Shaman
862 Stonard Explorer
861 Stonard Scout
865 Stonard Wayfinder
867 Stonard Cartographer
864 Stonard Orc
983 Thultazor
984 Thralosh
981 Hartash
987 Ogromm
985 Malosh
866 Stonard Grunt
988 Kartosh
1386 Rogvar (unsure)
1442 Helgrum (unsure)
1443 Fel'zerul (unsure)
1775 Zun'dartha (unsure)
- Model 2
3622 …
=> Swamp of Sorrows Improvement

etc/databases/world/updates/updates.sql
- Add, Tauren Bull Rush" (4083) spell to all classes
- Add, Tauren Bull Rush" (4083) button to all classes
- Removes elevators next to Freewind Post
- Updates Grimnal Display id
=> Updates to Issues: #416, #537, #550

etc/databases/world/updates/updates.sql
#455 #517 #518 #519 #520 #524 #534 #543
=> FIX #455 #517 #518 #519 #520 #524 #534 #543

etc/databases/world/updates/updates.sql
Change from 6 to 12 pyrewood shackles to finish the quest.
=> Fix issue #551

etc/databases/world/updates/updates.sql
Stormscale Siren  update
Gavin Gnarltree update
=> Closes: #558, #559, #565, #567, #572, #573, #575 

etc/databases/world/updates/updates.sql, tools/CreatureCacheParser.py
- FIX #583
-  FIX #584
- Add a parser for creatures (for version 3368 3494)
Thanks @devw4r
=> Fix #583 #584 and add creatures parser

etc/databases/world/updates/updates.sql
FIX
----
- #593
- #590
- #588
- #587
- #580
- #578
=> Display_id fix

game/world/managers/objects/units/creature/CreatureManager.py, utils/Formulas.py
=> Close #605

etc/databases/world/updates/updates.sql
#414 Defias Renegade Mage and Defias Profiteer not updated
=> Closes: #589, #586, partly: #414

game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/opcode_handling/handlers/interface/CharCreateHandler.py
/ Fixes not learning the required skill upon learning a new spell.. again.
/ Fixes block skill gain being always overrided by defense.
=> Close #614

game/world/WorldManager.py, game/world/managers/maps/GridManager.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/corpse/CorpseManager.py, game/world/managers/objects/dynamic/DynamicObjectManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/player/PlayerManager.py, utils/constants/MiscCodes.py
/ Basic DynamicObjectManager implementation.
/ Basic CorpseManager implementation, players should now leave corpses when dying.
=> Closes #610

game/world/WorldManager.py, game/world/managers/objects/units/player/quest/QuestManager.py, game/world/opcode_handling/handlers/player/MovementHandler.py, game/world/opcode_handling/handlers/quest/QuestGiverAcceptQuestHandler.py, game/world/opcode_handling/handlers/quest/QuestGiverChooseRewardHandler.py, game/world/opcode_handling/handlers/quest/QuestGiverCompleteQuestHandler.py, game/world/opcode_handling/handlers/quest/QuestGiverHelloHandler.py, game/world/opcode_handling/handlers/quest/QuestGiverQueryQuestHandler.py, game/world/opcode_handling/handlers/quest/QuestGiverRequestReward.py, game/world/opcode_handling/handlers/quest/QuestGiverStatusHandler.py, network/packet/PacketReader.py
=> Close #650

database/dbc/DbcDatabaseManager.py, database/world/WorldDatabaseManager.py, etc/databases/world/updates/updates.sql, game/world/managers/CommandManager.py, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/gameobjects/GameObjectBuilder.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/CooldownEntry.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/MovementManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/CreatureSpellsEntry.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/managers/objects/units/player/StatManager.py, game/world/managers/objects/units/player/TalentManager.py, game/world/managers/objects/units/player/quest/QuestHelpers.py, game/world/managers/objects/units/player/quest/QuestManager.py, game/world/opcode_handling/handlers/interface/CharCreateHandler.py, tools/ClassTrainersSkillsGenerator.py
/ Closes #648
/ Closes #653
/ Closes #635
/ Closes #613
/ Closes #615
/ Closes #525
/ Each class will now have & use the proper defense skills.
/ Add missing weapon skills to trainers and some missing spells.
=> / Quest, Weapon Trainers, Defense skills & others.

game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/DamageInfoHolder.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/SkillManager.py, game/world/managers/objects/units/player/StatManager.py, utils/Formulas.py
/ Closes #497
/ Closes #364
/ Fixes most of melee combat log displays (Miss, Parry, Dodge, Block, Absorb).
=> School absorb.

database/dbc/DbcDatabaseManager.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/player/SkillManager.py, tools/ClassTrainersSkillsGenerator.py
=> Closes #674

game/world/managers/objects/ObjectManager.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/spell/aura/AuraManager.py
* Force aura flag update on aura duration refresh
* Adds a temporary method for forcing a field update; TODO for @devw4r :^)
=> Fix visual bug with aura opacity

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellManager.py
* Fix harmfulness bug for spells with aura effects targeting both friendly and unfriendly targets
=> Add charm level restriction, improve effect harmfulness check

game/world/managers/objects/ObjectManager.py, game/world/managers/objects/spell/aura/AuraManager.py
- Do not clear the field but do touch the bitmask.
=> / Fix aura duration visual bug by other means.

etc/databases/world/updates/updates.sql
=> Closes #665 #666 #667

etc/databases/world/updates/updates.sql
Closes #644
Closes #657 
Closes #664 
Closes #677 
Closes #686 
Closes #689 
Note on #689 I didn't do anything with creature chaining as I couldn't figure out how that works
=> Fix several TODO Issues.

game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/DuelManager.py, game/world/managers/objects/units/player/PlayerManager.py
* Fix hostility checks for charmed units in duels
* Don't end duels for instant teleports (closes #705)
* Make blink behave as an instant teleport
=> Minor duel fixes

etc/databases/world/updates/updates.sql
Missing trainer spells after fixes in #703.
=> Missing trainer spells after fixes in #703.

game/world/managers/objects/gameobjects/GameObjectLootManager.py, game/world/managers/objects/loot/LootManager.py, game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/creature/CreatureLootManager.py, game/world/managers/objects/units/creature/CreaturePickPocketLootManager.py
- Orientation/Alive checks.
- Money generation.
=> Pick Pocket fixes.

etc/databases/world/updates/updates.sql
Closes #411 
Closes #560 
Closes #692 
Closes #693 
Closes #698 
Included is a fix for a previous pull request where a data entry error occurred.
=> Change Several Display ID's

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/units/PetManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/player/PlayerManager.py
- Fix charm spells not adding threat upon effect fading.
- Pet owner should now be added to target threat list and also enter combat upon pet damage.
- Thx @ratkosrb
=> Minor charm/threat fix.

game/world/managers/objects/corpse/CorpseManager.py
- Fix corpse not spawning in the proper map after resurrect.
=> Fix corpse.

etc/databases/dbc/updates/updates.sql, game/world/managers/maps/GridManager.py, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AppliedAura.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py, utils/constants/SpellCodes.py
- Closes #712
- Closes #722
- Closes #723
- Always send SMSG_SPELL_FAILURE for players/units if cast did not succeed. Might be related to #715
- Fix combat log duplicate messages due observers seeing update fields bit mask set on two consecutive ticks.
- Thx @Fluglow
=> Dispel & Others.

game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraManager.py
* Fix cooldown handling for spells with travel time (closes #716)
* Correct stealth aura interrupt logic
=> Minor spell fixes

game/world/managers/CommandManager.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py
- Units will now properly modify their weapons sheath state Normal/Ranged according to the current attack/spell.
=> Fix Units weapon sheath mechanics.

game/world/managers/maps/GridManager.py, game/world/managers/objects/corpse/CorpseManager.py, game/world/managers/objects/dynamic/DynamicObjectManager.py, game/world/managers/objects/units/PetManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureBuilder.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/CreatureSpawn.py, game/world/managers/objects/units/player/PlayerManager.py
- Closes #735
- Fix creature addon not being used.
- Use HIGHGUID_PET for permanent pets.
=> Pet portrait.

etc/databases/realm/updates/updates.sql, game/world/WorldLoader.py, game/world/WorldManager.py, game/world/managers/maps/CameraHolder.py, game/world/managers/maps/Cell.py, game/world/managers/maps/GridManager.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/dynamic/DynamicObjectManager.py, game/world/managers/objects/farsight/Camera.py, game/world/managers/objects/farsight/FarSightManager.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AppliedAura.py, game/world/managers/objects/spell/aura/AuraEffectDummyHandler.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/units/MovementManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureBuilder.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/GroupManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/handlers/group/MinimapPingHandler.py, game/world/opcode_handling/handlers/player/MovementHandler.py, utils/Logger.py, utils/constants/UnitCodes.py
- Spells like Eye of Kilrogg, Far Sight (PT),  Far Sight, Bind Sight & Sentry Totem now work.
- Fix summoned creatures using a Vector ref from owner instead of their own instance.
- Stop checking spell/aura move flags interrupts on network thread.
- Totems should no longer move... nor melee attack.
- Fix initial armor for creatures.
=> Some dummy auras and others.

game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py
* Closes #751
* Merge common health + mana/energy reset case into `replenish_power`
=> Fix health regeneration :skull:

game/world/managers/maps/Cell.py, game/world/managers/maps/GridManager.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/farsight/Camera.py, game/world/managers/objects/farsight/FarSightManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/MovementManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/opcode_handling/handlers/player/MovementHandler.py
=> Closes #750

game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/ThreatManager.py
=> Closes #754 #765

game/world/managers/objects/units/creature/CreatureBuilder.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py
Closes #759
- Fix pet portraits, again.
=> Closes #759

game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py
Closes #758 
- Rank1 is the only one applying SPELL_AURA_MOD_HEALTH_REGEN_PERCENT on caster, that's why upper ranks do not display an aura.
=> Closes #758

database/world/WorldDatabaseManager.py, database/world/WorldModels.py, etc/databases/world/updates/updates.sql, game/world/managers/objects/item/EnchantmentHolder.py, game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/EnchantmentManager.py
=> Closes #755

game/world/managers/objects/units/player/quest/QuestManager.py
=> Remove quest starting items when they're not required for the accepted quest

etc/databases/world/updates/updates.sql
Closes: #802 
Closes: #796 
Closes: #782 
Closes: #773 
Closes: #772 
Closes: #747 
Closes: #746 
Closes: #745 
Closes: #744 
Closes: #721
=> TODO: Display ID's

game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/SkillManager.py
* Apply shapeshift passives based on spell ID associations in `ShapeshiftInfo`
* Also apply passives for warrior stances
* Fix aura collision logic for passive spells
=> Shapeshift logic fix/refactor

database/realm/RealmDatabaseManager.py, game/world/managers/objects/units/player/GroupManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/handlers/interface/CharDeleteHandler.py
=> Closes #832

etc/databases/world/updates/updates.sql
Closes :  #816
Partial : #834
Ransin
-----
Evidences : NPC list from WorldOfWar
Update loc to Westfall
Bernie Heistein
-------
Evidences : NPC list form WorldOfWar
Spider trainer near Goldshire
Frank Lasson
------
This guy release position is Theramore inn, since he is a pet trainer, I relocated him outside in Theramore
Kenna Larnad
------
Same as Frank Lasson, I relocated her outside in Theramore
Talar
------
Evidences :  Allakhazam
Actually in Oracle Glade,  he should stand in Military ward Danassus.
Nadya Maneweaver
--------
Evidences : Allakhazam
Spawned at Oracle Glade. Become our refence for Nerra Cat Trainer
Nerra
-------
Evidences : Allakhazam
Spawned at Oracle glade near Nadya
Radnaal Maneweaver
--------
This guy was reference NPC for Nerra but he is not part of 0.5.3 (too high …
=> pet trainers minor fix

game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/handlers/player/cheats/BeastMasterHandler.py
=> Beastmaster

game/world/managers/CommandManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/player/cheats/CreateMonsterHandler.py, game/world/opcode_handling/handlers/player/cheats/DestroyMonsterHandler.py
- Added account level: Dev (2)
- Added 2 new Dev level console/chat commands: `createmonster` and `destroymonster`.
- Moved `worldoff` command from GM to Dev rank.
- Spawning and destroying creatures does not persist through server restart.
=> Command Improvements

game/world/managers/objects/units/UnitManager.py
* Remove damage from attack state updates
=> Fix melee abilities doing damage twice

game/world/managers/maps/MapManager.py, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/units/player/PlayerManager.py
=> Fix liquids warnings again..

game/world/managers/objects/spell/EffectTargets.py, game/world/opcode_handling/handlers/npc/TrainerBuySpellHandler.py
=> Minor crash fixes

game/world/managers/objects/units/creature/utils/TrainerUtils.py
- Fix Weapon Talents displaying subsequent, unavailable ranks as available.
- Closes #867
=> Weapon Talent Fix

game/world/managers/objects/spell/aura/AuraEffectDummyHandler.py, game/world/managers/objects/units/UnitManager.py
=> Spell damage and sentry totem crash fixes

game/world/managers/maps/GridManager.py, game/world/managers/maps/Map.py, game/world/managers/maps/MapManager.py, game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/ai/TotemAI.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/spell/aura/AuraEffectDummyHandler.py, game/world/managers/objects/units/PetManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py
- Closes #769
- Another crash due 'map_' -> 'map_id'
=> Closes #769

game/world/managers/maps/GridManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/EnchantmentManager.py
- Stop trying to apply empty item enchantments upon initialization, each of them triggering calls to StatManager apply_bonuses()..
=> EnchantmentManager

game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/StatManager.py
- Closes #883
- Invisiblity detection is now based purely on stat comparison. (Invisibility vs Invisiblity Detection mods).
=> Closes #883

game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/player/SkillManager.py
- Skills added from learning a spell should now properly be added without needing to relog. e.g. Mining, Herbalism, etc..
=> Fix skill learning bug.

game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/spell/SpellEffectHandler.py
=> Closes #888

Dockerfile, docker-compose.yml, etc/docker/main/Dockerfile, etc/docker/realm/Dockerfile, etc/docker/world/Dockerfile
Updated main container, and added realm and world.
=> updated docker compose stuff

docker-compose.yml
small updates to composer file
=> some updates to composer

etc/databases/world/updates/updates.sql, game/world/managers/objects/units/pet/ActivePet.py
This fixes issues #770 ("Stemming the Corruption" quest objective fix) and #822 (Stormwind rework)
=> Fix for #770 and #822

game/world/managers/objects/units/player/StatManager.py
* Fix spell miss modifier from resistance when skill difference is high
=> Fix resist modifier limits application

game/world/managers/objects/units/player/InventoryManager.py, game/world/opcode_handling/handlers/npc/PetitionBuyHandler.py
=> Fix inventory methods accessing bank items when not desired

game/world/managers/maps/MapManager.py
- Protect against namigator returning above terrain Z while monsters chase inside caves.
=> Namigator Z

game/world/managers/objects/units/creature/utils/TrainerUtils.py
* Fix crash when attempting to learn pet spells
* Fix trainer class for demon trainers
=> Pet training fixes

game/world/managers/objects/ObjectManager.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/units/creature/CreatureManager.py
Closes #612  (and also fixes Eliza's display_id)
Includes:
- moves ScriptHandler from ObjectManager to CreatureManager and GameObjectManager as it's not needed on everything
- improves handle_script_command_temp_summon_creature - it now spawns a temporary mob with no loot for despawn_type == 0. This is still not perfect, of course, but CreatureBuilder.create() simply doesn't know a despawn mode unless I am blind.
- fixes unique summon count which wasn't really working before
- **NEW** implements handle_quest_complete spell effect used by some quest items. Quest handling needs to be changed for this to actually do anything except sending the player the "objective complete" message.
- **NEW** implements script_command_start_movement using the new (waypoint) movement system
=> Scripting system fixes/additions

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/script/AIEventHandler.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/units/movement/behaviors/FearMovement.py, game/world/managers/objects/units/player/quest/QuestManager.py, utils/constants/MiscCodes.py, utils/constants/ScriptCodes.py
* Add missing None checks to script handlers
* Fix HP event checks
* Finish creature flee script implementation
* Fix creature AI spellcast crash
* Fix invalid field usage / arguments in script handlers
* Load AI events on creature init instead of on each call
=> Script handling refactoring and crash fixes

game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/units/movement/behaviors/WaypointMovement.py
=> Fix command_attack_start.

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/units/player/EnchantmentManager.py
* Implement `summon_object_wild` handler
* Provide location when relevant for scripted spellcasts (closes #391)
* Fix `EFFECT_SELECT` targeting for summon spells
* Force instant casts for creature spells when flagged for it
=> Script spellcast fixes

game/world/managers/objects/script/ScriptHandler.py
Grender's last change broke importing updates.sql since it causes invalid CREATE TABLE options.
=> Fix broken updates.sql import

game/world/managers/objects/script/ScriptHandler.py
Closes #920 
- Renames enchanting vendors to "Enchanter"/"Enchantress"
- removes "Bundle of Wood" from enchanting vendors; it's not enchanting related
- adds enchanting powder items to enchanting vendors
- adds ordered vendor template for tradeskill vendors
- assigns the new template to all tradeskill vendors
=> Enchanting & Tradeskill vendor rework

game/world/managers/objects/script/ScriptHandler.py
Closes #840 
Not moving NPCs because they are in the correct place in 0.5.3
=> Rename Old Town shop "The Five Deadly Venoms"

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/pet/ActivePet.py, game/world/managers/objects/units/pet/PetManager.py
* Fix infinite destroy() call loop on pet expiration
=> Restructure pet detach destroy order

database/world/WorldDatabaseManager.py, game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/script/AIEventHandler.py, game/world/managers/objects/script/ScriptManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/movement/behaviors/PetMovement.py
Closes #961
Fix PetMovement crash upon charm effect end.
=> Closes #961

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/spell/SpellEffectHandler.py
=> Add summon spell effect handler

game/world/opcode_handling/handlers/quest/QuestGiverHelloHandler.py
Pauses OOC movement for 180 seconds when a player talks to a questgiver.
=> Pause NPC movement when a player talks to them

game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/quest/ActiveQuest.py, game/world/managers/objects/units/player/quest/QuestManager.py
=> Closes #993

etc/databases/world/updates/updates.sql
Closes #983 
Also despawns the unused Tool Bucket gameobjects.
=> Hearthglen fixes

etc/databases/world/updates/updates.sql
Fixes SQL import issues introduced by malformed comments in #1017
=> Fix SQL comments

game/world/WorldManager.py, game/world/managers/objects/gameobjects/managers/TransportManager.py, game/world/managers/objects/loot/LootManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/movement/MovementInfo.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/npc/CreatureQueryHandler.py, game/world/opcode_handling/handlers/player/MovementHandler.py
- Update passengers Z on transport update. (Fixes anti cheat triggering @mindphluxnet)
- Remove players from transport before teleporting.
- Use UNIT_FLAG_PET_IN_COMBAT for pets. (Red flashing portrait)
- Minor refactor.
=> Transports

etc/databases/world/updates/updates.sql
Closes #1067 #1069 
Progress on #1070 #1016
We have screenshot proof of the location of some of the Programmer Isle NPCs so I thought I would spawn them in.
=> Spawn various NPCs + NPC Fixes

etc/databases/world/updates/updates.sql
Closes #1062 
Also fixes all squirrels looking like oversized humans ([see Discord](https://discord.com/channels/628574828038717470/628575889176920064/1089899551000899584))
=> Loch Modan rework

etc/databases/world/updates/updates.sql
Close https://github.com/The-Alpha-Project/alpha-core/issues/1016
Partial #1022 
Defias Renegade Mage
------------------------
About this https://github.com/The-Alpha-Project/alpha-core/issues/414
The fact that all the area were updated besides this only one defias mob is weird.
What we know is low entry human are always resolved by old human, for this case, by old defias
Since it's a caster, I applied standard defias caster male/female
=> Various NPCs Fixes

etc/databases/world/updates/updates.sql
Standard PH
==========
Closes #1095
Closes #1096
Closes #1097
Closes #1044
Partial #1094
Here is listing of unused unique display_id
```
UNIQUE MODELS (exclude placeholders, old humans models)
Dwarf female    : 0 unused models (one duplicates unused)
Dwarf male      : 2 unused unique models (one could be mountaineer placeholder)
Gnome female    : 0 unused models
Gnome male      : 1 unused unique models
Nightelf female : 0 unused models
Nightelf male   : 1 unused unique models (he could be Guild Tabard Designer)
Orc female      : 1 unused unique models (kind of placeholder)
Orc male        : 0 unused models
Troll female    : 0 unused models
Troll male      : 1 unused unique models
Tauren female   : 0 unused models
Tauren male     : 0 unused models (one duplicated unused)
Undead female   : …
```
=> Apply standard PH

etc/databases/world/updates/updates.sql
- Closes #1120 
- Closes #1119 
- Closes #1118 
- Closes #1103 and closes #842
- Closes #1035 
- Closes #582 by spawning the last pet for Valyen Wolfsong
The quest text we have on file suggests Lomac Gearstrip could be found in Tinker Town. The original text ([from Goblin Workshop](https://web.archive.org/web/20040901125131/http://www.goblinworkshop.com/quests/an-old-colleague.html)) doesn't suggest a location and also includes another small difference.
=> Database fixes

etc/databases/world/updates/updates.sql
=> Mobs display_id fixes

etc/databases/world/updates/updates.sql
=> Display_id fix for Ayanna Dawnrunner/Lady Moongazer

etc/databases/world/updates/updates.sql
=> Updated display_id for Krolg and Druid of NPCs

game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/movement/behaviors/ChaseMovement.py, utils/Formulas.py
- Fix set run command. (Should just modify a move flag, not speeds).
- Fix swimming state bug leaving npcs with flag on after exiting water upon evade.
- More tweaks to chase movement behavior, fix another facing issue, always run towards target last known location.
- Always broadcast move flags changes done through set_move_flag.
=> Minor fixes/tweaks.

game/world/managers/objects/units/player/quest/QuestManager.py
- Fix quest item reward choice not honoring offered item count.
=> Quest reward fix.

game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/aura/AppliedAura.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/spell/aura/AuraManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py, utils/constants/SpellCodes.py
* Fix immunity effects removing auras unaffected by immunity (Resurrection Sickness)
* Fix some auras applying through immunity effects
* Implement immunity handling against friendly effects (Cyclone, Abolish Magic etc.)
* Fix immunity effects canceling passive auras
* Fix aura friendliness bug for some spells with mixed/AoE targets
* Fix damage shield effects not triggering (Lightning Shield etc.)
* Simplify effect harmfulness logic
* Fix combo points (Overpower trigger) not hiding properly for warriors
=> Immunity and spell fixes

game/world/managers/objects/units/UnitManager.py
=> Closes #1173

etc/databases/world/updates/updates.sql
Closes #1167
Closes #1156
Closes #1155
Closes #1139
PARTIAL #1128
Closes #1077
Closes #1142
=> Various NPC fixes

etc/databases/world/updates/updates.sql
Easy display_id fixes with PH models or vanilla models for various mobs
=> Various Display_id Fixes

etc/databases/world/updates/updates.sql
=> Add waypoints for Hill Giant

etc/databases/world/updates/updates.sql
Closes #1190 
Closes #1193
PARTIAL #1149
also include some minor adjustements for grom gol.
=> Various Fixes

etc/databases/world/updates/updates.sql, game/world/managers/objects/units/movement/behaviors/WanderingMovement.py
- Closes #1181
- Closes #1087 (Was fixed at #1150)
- Wandering path validation should use last known unit location not spawn position.
=> Closes #1181

game/world/managers/objects/units/player/quest/ActiveQuest.py, game/world/managers/objects/units/player/quest/QuestManager.py
=> Closes #1189

game/world/managers/objects/units/player/quest/QuestManager.py
=> Closes #1182

etc/databases/world/updates/updates.sql
=> Closes #1143 #1124

game/world/managers/objects/units/player/quest/QuestManager.py
Closes #1091
Closes #1114
Closes #967
=> Closes #1091 #1114 #967

game/world/managers/objects/item/ItemLootManager.py, game/world/managers/objects/loot/LootManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/handlers/inventory/OpenItemHandler.py, game/world/opcode_handling/handlers/loot/AutostoreLootItemHandler.py, game/world/opcode_handling/handlers/spell/UseItemHandler.py
Closes #1006
Closes #1210
Other issues that should be closed already:
Closes #1104
Closes #636
Closes #807
Closes #975
=> Closes #1006 #1210

etc/databases/world/updates/updates.sql, game/world/managers/abstractions/Vector.py, game/world/managers/objects/loot/LootManager.py, game/world/managers/objects/script/AIEventHandler.py, game/world/managers/objects/units/movement/behaviors/WaypointMovement.py, game/world/managers/objects/units/movement/helpers/Spline.py
- Add Rite of Vision (Quest 772) waypoints for Plains Vision Wolf.
- Fix more scenarios where server side orientation would be wrong, specially on guessed locations in between waypoints.
- Captain EO, add dance emote upon quest completion.
=> Rite of Vision & orientation.

game/world/managers/objects/units/player/quest/ActiveQuest.py
- Fix quest related go's staying active after the related item was no longer needed.
=> Quest - Go Interaction.

etc/databases/world/updates/updates.sql, game/world/managers/objects/item/ItemManager.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/movement/MovementManager.py, game/world/managers/objects/units/movement/behaviors/ChaseMovement.py, game/world/managers/objects/units/movement/behaviors/FearMovement.py, game/world/managers/objects/units/movement/behaviors/WanderingMovement.py, game/world/managers/objects/units/movement/helpers/SplineEvent.py, game/world/opcode_handling/Definitions.py, game/world/opcode_handling/handlers/player/cheats/MakeMonsterAttackMeHandler.py
- Fix SCRIPT_COMMAND_EMOTE not using delays or restoring orientation.
- Fix SCRIPT_COMMAND_COMBAT_STOP.
- Fix SCRIPT_COMMAND_DESPAWN_CREATURE delay.
- Test with [The Deserters](https://db.thealphaproject.eu/index.php?action=show_quest&id=1286)
- Fix invalid faction 1070 for 14 (Monster: Not Social)
- Handle assist seek for low hp fleeing events.
- Closes #1209
- Fix Items 'Created By' attribute.
- Elder Crag Boar should use Boar Charge.
- MakeMonsterAttackMe handler.
- Wandering - Use LoS check for point validation.
- Closes #502 (Already working)
- Fix bug with MOVEFLAG_SWIMMING being wrongfuly removed.
=> Multiple Fixes.

game/world/managers/abstractions/Vector.py, game/world/managers/objects/spell/EffectTargets.py
* Merge target filtering into one method to avoid multiple iterations
* Fix creature type restriction not applying past initial target
* Fix chain damage distance check
* Use squared distance for ranged checks
=> Refactor and optimize target resolving

etc/databases/world/custom/scarlet_monastery_teleporter.sql, etc/databases/world/updates/updates.sql
Add teleporter in front of Scarlet monastery gates to be able to access it for players
thanks @devw4r
=> Scarlet Monastery GO Teleporter

game/world/managers/objects/units/player/PlayerManager.py, game/world/opcode_handling/handlers/player/PlayerLoginHandler.py
- Fix spell passives not being set if the user logged in while being dead. @Fluglow
=> Minor fix.

etc/databases/world/updates/updates.sql, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py
=> Closes #1234

game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/DamageInfoHolder.py, game/world/managers/objects/units/UnitManager.py
Missing fix for #1228
Closes #1221
=> Closes #1221

game/world/managers/maps/MapManager.py
- Fixes reported case of mobs disappearing on the cave near Deathknell.
=> Bring back namigator Z protection..

etc/databases/world/updates/updates.sql, game/world/managers/maps/MapEventManager.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/script/ScriptedEvent.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/movement/MovementManager.py, game/world/managers/objects/units/movement/behaviors/EvadeMovement.py, game/world/managers/objects/units/player/quest/QuestManager.py
- Fix events failing prematurely when no event time was set.
- Fix fail quest script handler crash.
- Fix events not being removed from MapEventManager after success/failure condition was met.
- Make threat holders sorting stable.
=> Script quest - Missing in Action

etc/databases/world/updates/updates.sql
=>   Changes to the "Watcher Callahan" quest.sql

game/world/managers/objects/units/player/StatManager.py
=> Stamina class based

etc/databases/world/updates/updates.sql, game/world/managers/objects/script/ScriptHandler.py
=> Scarlet Monastery Adjustements and more

etc/databases/world/updates/updates.sql
=> Change the In Defense of the King's Lands experience and currency reward

etc/databases/world/updates/updates.sql
Closes #1294
Closes #1161
Closes #1306
Closes #1305
Closes #1291
Closes #1313
Spawn Elem https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/from_alpha_archive_30082023/waterelementals.jpg
=> Random fixes

database/world/WorldDatabaseManager.py, game/world/managers/CommandManager.py
Command .gocreature
========
- Works as `.tel` but for creatures
- Not case sensitive, not space sensitive
Usage
--------
`.gocreature thrall`
`.gocreature lesserwaterlemental`
`.gocreature magni`
`.gocreature Zardeth Of the Black Claw`
these different commands below will give you the same result : 
`.gocreature strumner`
`.gocreature strumnerflintheel`
`.gocreature Strumner flintheel`
`.gocreature flintheel`
=> Command .gocreature

etc/databases/world/updates/updates.sql
Items fixes
======
NOTES :  with this PR we can notice this regarding the missing display_id
Display_id are missing for mostly 2 reasons
- Icons have been  changed because it was not appropriate for the display_id but the model stayed the same, it what we see most of the time, in this case we need to look at the 1.12 model to find the same one
- Models and Icons have been changed, in this case, the item most likely use a PH model
Offhand
--------
https://models.thealphaproject.eu/Offhand
We have only few offhand models for 0.5.3, they were updated with some colors/models variations later and that's why we miss them.
VANILLA MODELS
0.5.3 MODELS
Quiver
-------
Since quiver have no models, we will use a PH icons for 3 of them (first quiver icon ever avalaible)
Skullflame
---------- …
=> items fixes

etc/databases/world/updates/updates.sql
Cowl of Necrology
------------
Craftsman Monocle
---------
Crochet Belt
-------
Enduring Cap
--------
It's updated icon here display_id here
Augural Shroud
-----
Black Velvet Robe
-------
Blackforge Cowl
---
Brigandine Helm
------
Cloaked Hood
-----
=> Some Items Fixes

etc/docker/main/Dockerfile, etc/docker/realm/Dockerfile, etc/docker/sql/Dockerfile, etc/docker/world/Dockerfile
main, realm, world to python:alpine-3.12 and MariaDB to 1.11.2
=> updated docker,

etc/databases/world/updates/updates.sql
=> Items display fixes

etc/databases/world/updates/updates.sql
Closes #1333 
Closes #1332 
Closes #1338
Closes #1285 
Closes #1280 
Closes #1295 
Closes #1296 
Closes #1298 
Closes #1299 
Closes #1300 
Closes #1302
Closes #1327
=> Several minor fixes

game/world/managers/CommandManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/pet/ActivePet.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py
* Move all creature stat handling to `StatManager`
* Creature base stats are now included in stat calculations, allowing them to benefit from buffs
* Pet stats are also handled within the same workflow
* Add `ATTACK_POWER` to `UnitStats` and related logic to `StatManager`
* Implement `.addaura` and `.clearaura` commands for testing
* Fix magic resistances not being applied correctly
Refactoring:
* Move unit attribute fields from `PlayerManager` to `UnitManager`
* Combine unit resistance fields to a single list to reduce duplicate code
* Split creature-specific logic from `StatManager.calculate_item_stats` to `StatManager._set_creature_base_damage`
=> Creature stat handling fixes and refactoring

game/world/managers/objects/spell/SpellEffect.py
* Check implicit unit target if needed in `_resolve_harmful` when validating cast
=> Fix charge target resolving

etc/databases/world/updates/updates.sql
closes #1361
closes #1360
closes #1335
=> Closes #1361 #1360 #1335

etc/databases/world/updates/updates.sql, game/world/managers/objects/ObjectManager.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/spell/CastingSpell.py, game/world/managers/objects/spell/EffectTargets.py, game/world/managers/objects/spell/SpellManager.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py
* Add scripts for Defias Cannon door activation and Defias Gunpowder event
* Fix open doors having collision after relogging
* Fix summoned creatures despawning instantly on death (fixes [Sneed](https://db.thealphaproject.eu/index.php?action=show_creature&id=643) never being lootable)
* Fix crash on [Melt Ore](https://db.thealphaproject.eu/index.php?action=show_spell&id=5159) target resolving
* Fix mana regen being disrupted by abilities / tradeskills
* Fix base mana regen
=> Deadmines scripting / various bug fixes

etc/databases/world/updates/updates.sql
Potions Icons
=====
https://crawler.thealphaproject.eu/mnt/crawler/media/Website/wow.gamona.de/web.archive.org/web/20041222212102/http:/wow.gamona.de/index.php%3Fseite=items&group=11&type=1111.html
=> Potion fixes

database/dbc/DbcDatabaseManager.py, database/realm/RealmDatabaseManager.py, database/world/WorldDatabaseManager.py, etc/config/config.yml.dist
Environment variable name according to:
https://mariadb.com/kb/en/mariadb-environment-variables/
=> Allow to specify database port in config.yml

game/world/managers/objects/gameobjects/GameObjectBuilder.py, game/world/managers/objects/gameobjects/GameObjectManager.py, game/world/managers/objects/units/creature/CreatureBuilder.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/pet/ActivePet.py, game/world/managers/objects/units/pet/PetManager.py
- Fixes summoned pets not being despawned due changes made on 2398e30891c241984797a3707f59fddeab306076
=> Fix pets detach bug reported by Alonin.

game/world/managers/maps/MapManager.py
- Fix LoS checks returning TRUE when the tile data is still being loaded. (Fixes mobs aggroing through walls upon entering Shadowfang for the first time).
=> Fix line of sight.

game/world/managers/objects/ai/CreatureAI.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/movement/MovementManager.py, game/world/managers/objects/units/movement/behaviors/ConfusedMovement.py, game/world/managers/objects/units/movement/behaviors/FearMovement.py, game/world/managers/objects/units/movement/behaviors/WanderingMovement.py, utils/constants/MiscCodes.py
- Initial handling for SPELL_AURA_MOD_CONFUSE.
=> SPELL_AURA_MOD_CONFUSE

etc/databases/world/updates/updates.sql
=> Closes #1391

game/world/managers/objects/units/movement/behaviors/FlightMovement.py, game/world/managers/objects/units/player/taxi/TaxiManager.py
=> Closes #1390

etc/databases/world/updates/updates.sql
Closes #1149
@GizzleBizzle please open two new issues regarding Gol'Bolar and The Quarry events.
=> Closes #1149

game/world/managers/objects/script/AIEventHandler.py, game/world/managers/objects/script/ScriptCreatureAIEvent.py, game/world/managers/objects/script/ScriptManager.py
=> Closes #1401

game/world/managers/objects/script/ConditionChecker.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/movement/behaviors/GroupMovement.py, game/world/managers/objects/units/movement/behaviors/WaypointMovement.py
Closes #1398 (Also Defias Traitor should now run instead of walk the whole path..)
=> Closes #1398

etc/databases/world/updates/updates.sql, game/world/managers/objects/script/ConditionChecker.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/spell/SpellEffectHandler.py, game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/units/player/PlayerManager.py
- More fixes to invalid creature spells on scripts.
=> Script spells.

game/world/managers/objects/units/pet/PetManager.py
=> Modify tame level restriction.

etc/databases/world/updates/updates.sql, game/world/managers/objects/locks/LockManager.py, game/world/managers/objects/spell/ExtendedSpellData.py, game/world/managers/objects/units/creature/CreatureManager.py, game/world/managers/objects/units/creature/ThreatManager.py, game/world/managers/objects/units/creature/utils/TrainerUtils.py, game/world/managers/objects/units/movement/behaviors/FearMovement.py, game/world/managers/objects/units/player/SkillManager.py, game/world/opcode_handling/handlers/npc/TrainerListHandler.py
Closes #1433
- Fixes to creatures fear assist / call for help logic.
- Fix creatures not finishing evading (return to home) if the player logs out and no other player is near.
-Issues that should be closed:
Closes #1379 (No longer an issue)
Closes #1170 (No longer an issue)
Closes #906 (Client issue)
Closes #808  (No longer an issue)
Closes #512 (Tracking spells (From Tracking skill) were not usable)
Closes #269 (Pooling)
=> Closes #1433

etc/databases/world/updates/updates.sql
closes #1452
closes #1451
closes #1450
closes #1394
closes #1456 
closes #1454
closes #1163
#1449 (Mymidon Signet)
#1304 (Kitari Farseeker Cartography Trainer)
#1430 (Levels and Ranks)
#1457 (Binders)
closes #1440 could be closed if @devw4r agrees
move Maginor
=> closes #1452 #1451 #1450 #1394

etc/databases/world/updates/updates.sql
Restores some of the unused and deprecated items that possibly or certainly existed in Alpha 0.5.3 according to this issue: https://github.com/The-Alpha-Project/alpha-core/issues/1447. Note that I have not covered every item, and some of the items changed still have no in-game source. The items I have changed area as follows:
- Deprecated Captain Sander's Eyepatch : Added as a reward from Captain Sander's Hidden Treasure replacing the Silver Bar. Deprecated tag removed. Proper quality added.
- Aegis of Westfall : Added as a reward from The Defias Brotherhood. Never had a deprecated tag.
- Mark of the Kirin Tor : Added as a drop from Dalaran Summoner. Never had a deprecated tag.
- Deprecated Whisperwind Headdress : Added as a reward from Isha Hawk. Deprecated tag removed. Stats of the …
=> Deprecated Item Restoration Part 1

game/world/managers/objects/spell/aura/AuraEffectHandler.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/creature/CreatureManager.py
* Closes #1461
* Make all immunity checks use masks to support database values
* Move removing immunities to a separate method to simplify `set_immunity` parameters
* Combine friendly immunity check into `has_immunity`
=> Implement innate creature immunities + refactor immunity handling

game/world/managers/objects/gameobjects/managers/DoorManager.py
=> Fix opening doors with no auto-close timer

README.md, database/realm/RealmDatabaseManager.py, database/world/WorldDatabaseManager.py, etc/config/config.yml.dist, game/world/managers/maps/InstancesManager.py, game/world/managers/maps/MapTile.py, game/world/managers/objects/script/ScriptHandler.py, game/world/managers/objects/units/movement/behaviors/FearMovement.py, game/world/managers/objects/units/player/GroupManager.py, game/world/managers/objects/units/player/InventoryManager.py, game/world/managers/objects/units/player/quest/QuestManager.py, game/world/opcode_handling/handlers/loot/LootRequestHandler.py, game/world/opcode_handling/handlers/player/MovementHandler.py, main.py, tools/extractors/NavExtractor.py, tools/extractors/definitions/chunks/MCLQ.py, tools/extractors/pydbclib/DbcReader.py, utils/ConfigManager.py, utils/PathManager.py, utils/SysUtils.py
- Fix nav extractor exception on Windows related to mapbuild import.
- Fix nav extractor failing due os file handle limit on Linux/Mac.
- Update readme.
=> Nav extraction fixes.

etc/databases/world/updates/updates.sql, game/world/managers/objects/spell/SpellEffect.py, game/world/managers/objects/spell/aura/AuraEffectDummyHandler.py, game/world/managers/objects/units/UnitManager.py, game/world/managers/objects/units/pet/PetData.py, game/world/managers/objects/units/player/PlayerManager.py, game/world/managers/objects/units/player/StatManager.py
* Trigger damage interrupt for auras on periodic damage (closes #1497)
* Fix hunter pets gaining experience past owner level
* Fix unreasonably high spell resist chance against higher level creatures
* Fix inconsistent rounding in mp5/hp5 calculations
* Fix training level requirement for some pet abilities
=> Various bug fixes / refactoring

etc/databases/world/updates/updates.sql, game/world/managers/abstractions/Vector.py, game/world/managers/maps/Cell.py
- Spawn Lok Orcbane, fixes quest Betrayal from Within.
- Use 2d distance for VIEW_DISTANCE checks, fixes reported issue @ UC.
=> Spawn Lok Orcbane and view distance fix.
